package com.edu.ccut.dao;

import com.edu.ccut.pojo.Comment;

public interface CommentMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment
	 * @mbggenerated  Sun Jul 31 14:34:41 CST 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment
	 * @mbggenerated  Sun Jul 31 14:34:41 CST 2016
	 */
	int insert(Comment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment
	 * @mbggenerated  Sun Jul 31 14:34:41 CST 2016
	 */
	int insertSelective(Comment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment
	 * @mbggenerated  Sun Jul 31 14:34:41 CST 2016
	 */
	Comment selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment
	 * @mbggenerated  Sun Jul 31 14:34:41 CST 2016
	 */
	int updateByPrimaryKeySelective(Comment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table comment
	 * @mbggenerated  Sun Jul 31 14:34:41 CST 2016
	 */
	int updateByPrimaryKey(Comment record);
}