package com.edu.ccut.dao;

import com.edu.ccut.pojo.Focus;
import com.edu.ccut.pojo.FocusExample;
import java.util.List;

public interface FocusMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table focus
	 * @mbggenerated  Mon Jan 02 17:35:41 CST 2017
	 */
	int countByExample(FocusExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table focus
	 * @mbggenerated  Mon Jan 02 17:35:41 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table focus
	 * @mbggenerated  Mon Jan 02 17:35:41 CST 2017
	 */
	int insert(Focus record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table focus
	 * @mbggenerated  Mon Jan 02 17:35:41 CST 2017
	 */
	int insertSelective(Focus record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table focus
	 * @mbggenerated  Mon Jan 02 17:35:41 CST 2017
	 */
	List<Focus> selectByExample(FocusExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table focus
	 * @mbggenerated  Mon Jan 02 17:35:41 CST 2017
	 */
	Focus selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table focus
	 * @mbggenerated  Mon Jan 02 17:35:41 CST 2017
	 */
	int updateByPrimaryKeySelective(Focus record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table focus
	 * @mbggenerated  Mon Jan 02 17:35:41 CST 2017
	 */
	int updateByPrimaryKey(Focus record);
}