package com.edu.ccut.dao;

import com.edu.ccut.pojo.Laud;
import com.edu.ccut.pojo.LaudExample;
import java.util.List;

public interface LaudMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table laud
	 * @mbggenerated  Mon Jan 02 17:35:41 CST 2017
	 */
	int countByExample(LaudExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table laud
	 * @mbggenerated  Mon Jan 02 17:35:41 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table laud
	 * @mbggenerated  Mon Jan 02 17:35:41 CST 2017
	 */
	int insert(Laud record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table laud
	 * @mbggenerated  Mon Jan 02 17:35:41 CST 2017
	 */
	int insertSelective(Laud record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table laud
	 * @mbggenerated  Mon Jan 02 17:35:41 CST 2017
	 */
	List<Laud> selectByExample(LaudExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table laud
	 * @mbggenerated  Mon Jan 02 17:35:41 CST 2017
	 */
	Laud selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table laud
	 * @mbggenerated  Mon Jan 02 17:35:41 CST 2017
	 */
	int updateByPrimaryKeySelective(Laud record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table laud
	 * @mbggenerated  Mon Jan 02 17:35:41 CST 2017
	 */
	int updateByPrimaryKey(Laud record);
}