package com.edu.ccut.dao;

import com.edu.ccut.pojo.Laud;

public interface LaudMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table laud
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table laud
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	int insert(Laud record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table laud
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	int insertSelective(Laud record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table laud
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	Laud selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table laud
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	int updateByPrimaryKeySelective(Laud record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table laud
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	int updateByPrimaryKey(Laud record);
}