package com.edu.ccut.dao;

import com.edu.ccut.pojo.Member;
import com.edu.ccut.pojo.MemberKey;

public interface MemberMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	int deleteByPrimaryKey(MemberKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	int insert(Member record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	int insertSelective(Member record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	Member selectByPrimaryKey(MemberKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	int updateByPrimaryKeySelective(Member record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	int updateByPrimaryKey(Member record);

	Member getMemberByEmail(String email);
}