package com.edu.ccut.dao;

import com.edu.ccut.pojo.Person;
import com.edu.ccut.pojo.PersonExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PersonMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table person
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	int countByExample(PersonExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table person
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	int deleteByExample(PersonExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table person
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table person
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	int insert(Person record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table person
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	int insertSelective(Person record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table person
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	List<Person> selectByExample(PersonExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table person
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	Person selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table person
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	int updateByExampleSelective(@Param("record") Person record, @Param("example") PersonExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table person
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	int updateByExample(@Param("record") Person record, @Param("example") PersonExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table person
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	int updateByPrimaryKeySelective(Person record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table person
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	int updateByPrimaryKey(Person record);
	
	List<Person> getAllPerson();
}