package com.edu.ccut.pojo;

import java.util.Date;

public class Comment {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comment.id
	 * @mbggenerated  Sun Jul 31 14:34:41 CST 2016
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comment.commentfrom
	 * @mbggenerated  Sun Jul 31 14:34:41 CST 2016
	 */
	private Integer commentfrom;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comment.commentto
	 * @mbggenerated  Sun Jul 31 14:34:41 CST 2016
	 */
	private Integer commentto;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comment.commentinfo
	 * @mbggenerated  Sun Jul 31 14:34:41 CST 2016
	 */
	private String commentinfo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comment.circle
	 * @mbggenerated  Sun Jul 31 14:34:41 CST 2016
	 */
	private String circle;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comment.commentdate
	 * @mbggenerated  Sun Jul 31 14:34:41 CST 2016
	 */
	private Date commentdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comment.state
	 * @mbggenerated  Sun Jul 31 14:34:41 CST 2016
	 */
	private Integer state;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comment.commentflag
	 * @mbggenerated  Sun Jul 31 14:34:41 CST 2016
	 */
	private Integer commentflag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comment.r1
	 * @mbggenerated  Sun Jul 31 14:34:41 CST 2016
	 */
	private String r1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comment.r2
	 * @mbggenerated  Sun Jul 31 14:34:41 CST 2016
	 */
	private String r2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comment.r3
	 * @mbggenerated  Sun Jul 31 14:34:41 CST 2016
	 */
	private String r3;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comment.id
	 * @return  the value of comment.id
	 * @mbggenerated  Sun Jul 31 14:34:41 CST 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comment.id
	 * @param id  the value for comment.id
	 * @mbggenerated  Sun Jul 31 14:34:41 CST 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comment.commentfrom
	 * @return  the value of comment.commentfrom
	 * @mbggenerated  Sun Jul 31 14:34:41 CST 2016
	 */
	public Integer getCommentfrom() {
		return commentfrom;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comment.commentfrom
	 * @param commentfrom  the value for comment.commentfrom
	 * @mbggenerated  Sun Jul 31 14:34:41 CST 2016
	 */
	public void setCommentfrom(Integer commentfrom) {
		this.commentfrom = commentfrom;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comment.commentto
	 * @return  the value of comment.commentto
	 * @mbggenerated  Sun Jul 31 14:34:41 CST 2016
	 */
	public Integer getCommentto() {
		return commentto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comment.commentto
	 * @param commentto  the value for comment.commentto
	 * @mbggenerated  Sun Jul 31 14:34:41 CST 2016
	 */
	public void setCommentto(Integer commentto) {
		this.commentto = commentto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comment.commentinfo
	 * @return  the value of comment.commentinfo
	 * @mbggenerated  Sun Jul 31 14:34:41 CST 2016
	 */
	public String getCommentinfo() {
		return commentinfo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comment.commentinfo
	 * @param commentinfo  the value for comment.commentinfo
	 * @mbggenerated  Sun Jul 31 14:34:41 CST 2016
	 */
	public void setCommentinfo(String commentinfo) {
		this.commentinfo = commentinfo == null ? null : commentinfo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comment.circle
	 * @return  the value of comment.circle
	 * @mbggenerated  Sun Jul 31 14:34:41 CST 2016
	 */
	public String getCircle() {
		return circle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comment.circle
	 * @param circle  the value for comment.circle
	 * @mbggenerated  Sun Jul 31 14:34:41 CST 2016
	 */
	public void setCircle(String circle) {
		this.circle = circle == null ? null : circle.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comment.commentdate
	 * @return  the value of comment.commentdate
	 * @mbggenerated  Sun Jul 31 14:34:41 CST 2016
	 */
	public Date getCommentdate() {
		return commentdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comment.commentdate
	 * @param commentdate  the value for comment.commentdate
	 * @mbggenerated  Sun Jul 31 14:34:41 CST 2016
	 */
	public void setCommentdate(Date commentdate) {
		this.commentdate = commentdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comment.state
	 * @return  the value of comment.state
	 * @mbggenerated  Sun Jul 31 14:34:41 CST 2016
	 */
	public Integer getState() {
		return state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comment.state
	 * @param state  the value for comment.state
	 * @mbggenerated  Sun Jul 31 14:34:41 CST 2016
	 */
	public void setState(Integer state) {
		this.state = state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comment.commentflag
	 * @return  the value of comment.commentflag
	 * @mbggenerated  Sun Jul 31 14:34:41 CST 2016
	 */
	public Integer getCommentflag() {
		return commentflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comment.commentflag
	 * @param commentflag  the value for comment.commentflag
	 * @mbggenerated  Sun Jul 31 14:34:41 CST 2016
	 */
	public void setCommentflag(Integer commentflag) {
		this.commentflag = commentflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comment.r1
	 * @return  the value of comment.r1
	 * @mbggenerated  Sun Jul 31 14:34:41 CST 2016
	 */
	public String getR1() {
		return r1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comment.r1
	 * @param r1  the value for comment.r1
	 * @mbggenerated  Sun Jul 31 14:34:41 CST 2016
	 */
	public void setR1(String r1) {
		this.r1 = r1 == null ? null : r1.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comment.r2
	 * @return  the value of comment.r2
	 * @mbggenerated  Sun Jul 31 14:34:41 CST 2016
	 */
	public String getR2() {
		return r2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comment.r2
	 * @param r2  the value for comment.r2
	 * @mbggenerated  Sun Jul 31 14:34:41 CST 2016
	 */
	public void setR2(String r2) {
		this.r2 = r2 == null ? null : r2.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comment.r3
	 * @return  the value of comment.r3
	 * @mbggenerated  Sun Jul 31 14:34:41 CST 2016
	 */
	public String getR3() {
		return r3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comment.r3
	 * @param r3  the value for comment.r3
	 * @mbggenerated  Sun Jul 31 14:34:41 CST 2016
	 */
	public void setR3(String r3) {
		this.r3 = r3 == null ? null : r3.trim();
	}
}