package com.edu.ccut.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class Company {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column company.id
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column company.unitaccnum
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	private String unitaccnum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column company.unitaccname
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	private String unitaccname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column company.orgcode
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	private String orgcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column company.unitchar
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	private String unitchar;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column company.unitkind
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	private String unitkind;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column company.salarydate
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	private String salarydate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column company.unitphone
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	private String unitphone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column company.unitlinkman
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	private String unitlinkman;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column company.unitagentpapno
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	private String unitagentpapno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column company.accstate
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	private Integer accstate = 0;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column company.balance
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	private BigDecimal balance = BigDecimal.valueOf(0.00);
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column company.basenumber
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	private BigDecimal basenumber = BigDecimal.valueOf(0.00);
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column company.unitprop
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	private BigDecimal unitprop;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column company.perprop
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	private BigDecimal perprop;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column company.unitpaysum
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	private BigDecimal unitpaysum = BigDecimal.valueOf(0.00);
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column company.perpaysum
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	private BigDecimal perpaysum = BigDecimal.valueOf(0.00);
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column company.persnum
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	private Integer persnum = 0;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column company.lastpaydate
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	private Date lastpaydate = new Date();
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column company.instcode
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	private String instcode = "0110";
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column company.op
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	private String op = "111111";
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column company.createdate
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	private Date createdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column company.remark
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	private String remark;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column company.r1
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	private String r1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column company.r2
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	private String r2;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column company.id
	 * @return  the value of company.id
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column company.id
	 * @param id  the value for company.id
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column company.unitaccnum
	 * @return  the value of company.unitaccnum
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	public String getUnitaccnum() {
		return unitaccnum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column company.unitaccnum
	 * @param unitaccnum  the value for company.unitaccnum
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	public void setUnitaccnum(String unitaccnum) {
		this.unitaccnum = unitaccnum == null ? null : unitaccnum.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column company.unitaccname
	 * @return  the value of company.unitaccname
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	public String getUnitaccname() {
		return unitaccname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column company.unitaccname
	 * @param unitaccname  the value for company.unitaccname
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	public void setUnitaccname(String unitaccname) {
		this.unitaccname = unitaccname == null ? null : unitaccname.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column company.orgcode
	 * @return  the value of company.orgcode
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	public String getOrgcode() {
		return orgcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column company.orgcode
	 * @param orgcode  the value for company.orgcode
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	public void setOrgcode(String orgcode) {
		this.orgcode = orgcode == null ? null : orgcode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column company.unitchar
	 * @return  the value of company.unitchar
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	public String getUnitchar() {
		return unitchar;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column company.unitchar
	 * @param unitchar  the value for company.unitchar
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	public void setUnitchar(String unitchar) {
		this.unitchar = unitchar == null ? null : unitchar.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column company.unitkind
	 * @return  the value of company.unitkind
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	public String getUnitkind() {
		return unitkind;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column company.unitkind
	 * @param unitkind  the value for company.unitkind
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	public void setUnitkind(String unitkind) {
		this.unitkind = unitkind == null ? null : unitkind.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column company.salarydate
	 * @return  the value of company.salarydate
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	public String getSalarydate() {
		return salarydate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column company.salarydate
	 * @param salarydate  the value for company.salarydate
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	public void setSalarydate(String salarydate) {
		this.salarydate = salarydate == null ? null : salarydate.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column company.unitphone
	 * @return  the value of company.unitphone
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	public String getUnitphone() {
		return unitphone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column company.unitphone
	 * @param unitphone  the value for company.unitphone
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	public void setUnitphone(String unitphone) {
		this.unitphone = unitphone == null ? null : unitphone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column company.unitlinkman
	 * @return  the value of company.unitlinkman
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	public String getUnitlinkman() {
		return unitlinkman;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column company.unitlinkman
	 * @param unitlinkman  the value for company.unitlinkman
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	public void setUnitlinkman(String unitlinkman) {
		this.unitlinkman = unitlinkman == null ? null : unitlinkman.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column company.unitagentpapno
	 * @return  the value of company.unitagentpapno
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	public String getUnitagentpapno() {
		return unitagentpapno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column company.unitagentpapno
	 * @param unitagentpapno  the value for company.unitagentpapno
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	public void setUnitagentpapno(String unitagentpapno) {
		this.unitagentpapno = unitagentpapno == null ? null : unitagentpapno.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column company.accstate
	 * @return  the value of company.accstate
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	public Integer getAccstate() {
		return accstate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column company.accstate
	 * @param accstate  the value for company.accstate
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	public void setAccstate(Integer accstate) {
		this.accstate = accstate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column company.balance
	 * @return  the value of company.balance
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	public BigDecimal getBalance() {
		return balance;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column company.balance
	 * @param balance  the value for company.balance
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	public void setBalance(BigDecimal balance) {
		this.balance = balance;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column company.basenumber
	 * @return  the value of company.basenumber
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	public BigDecimal getBasenumber() {
		return basenumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column company.basenumber
	 * @param basenumber  the value for company.basenumber
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	public void setBasenumber(BigDecimal basenumber) {
		this.basenumber = basenumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column company.unitprop
	 * @return  the value of company.unitprop
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	public BigDecimal getUnitprop() {
		return unitprop;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column company.unitprop
	 * @param unitprop  the value for company.unitprop
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	public void setUnitprop(BigDecimal unitprop) {
		this.unitprop = unitprop;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column company.perprop
	 * @return  the value of company.perprop
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	public BigDecimal getPerprop() {
		return perprop;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column company.perprop
	 * @param perprop  the value for company.perprop
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	public void setPerprop(BigDecimal perprop) {
		this.perprop = perprop;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column company.unitpaysum
	 * @return  the value of company.unitpaysum
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	public BigDecimal getUnitpaysum() {
		return unitpaysum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column company.unitpaysum
	 * @param unitpaysum  the value for company.unitpaysum
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	public void setUnitpaysum(BigDecimal unitpaysum) {
		this.unitpaysum = unitpaysum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column company.perpaysum
	 * @return  the value of company.perpaysum
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	public BigDecimal getPerpaysum() {
		return perpaysum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column company.perpaysum
	 * @param perpaysum  the value for company.perpaysum
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	public void setPerpaysum(BigDecimal perpaysum) {
		this.perpaysum = perpaysum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column company.persnum
	 * @return  the value of company.persnum
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	public Integer getPersnum() {
		return persnum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column company.persnum
	 * @param persnum  the value for company.persnum
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	public void setPersnum(Integer persnum) {
		this.persnum = persnum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column company.lastpaydate
	 * @return  the value of company.lastpaydate
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	public Date getLastpaydate() {
		return lastpaydate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column company.lastpaydate
	 * @param lastpaydate  the value for company.lastpaydate
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	public void setLastpaydate(Date lastpaydate) {
		this.lastpaydate = lastpaydate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column company.instcode
	 * @return  the value of company.instcode
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	public String getInstcode() {
		return instcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column company.instcode
	 * @param instcode  the value for company.instcode
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	public void setInstcode(String instcode) {
		this.instcode = instcode == null ? null : instcode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column company.op
	 * @return  the value of company.op
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	public String getOp() {
		return op;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column company.op
	 * @param op  the value for company.op
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	public void setOp(String op) {
		this.op = op == null ? null : op.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column company.createdate
	 * @return  the value of company.createdate
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	public Date getCreatedate() {
		return createdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column company.createdate
	 * @param createdate  the value for company.createdate
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column company.remark
	 * @return  the value of company.remark
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column company.remark
	 * @param remark  the value for company.remark
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	public void setRemark(String remark) {
		this.remark = remark == null ? null : remark.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column company.r1
	 * @return  the value of company.r1
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	public String getR1() {
		return r1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column company.r1
	 * @param r1  the value for company.r1
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	public void setR1(String r1) {
		this.r1 = r1 == null ? null : r1.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column company.r2
	 * @return  the value of company.r2
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	public String getR2() {
		return r2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column company.r2
	 * @param r2  the value for company.r2
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	public void setR2(String r2) {
		this.r2 = r2 == null ? null : r2.trim();
	}
}