package com.edu.ccut.pojo;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class CompanyExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table company
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table company
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table company
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table company
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	public CompanyExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table company
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table company
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table company
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table company
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table company
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table company
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table company
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table company
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table company
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table company
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table company
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		protected void addCriterionForJDBCDate(String condition, Date value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value.getTime()), property);
		}

		protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property + " cannot be null or empty");
			}
			List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
			Iterator<Date> iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(iter.next().getTime()));
			}
			addCriterion(condition, dateList, property);
		}

		protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andUnitaccnumIsNull() {
			addCriterion("unitaccnum is null");
			return (Criteria) this;
		}

		public Criteria andUnitaccnumIsNotNull() {
			addCriterion("unitaccnum is not null");
			return (Criteria) this;
		}

		public Criteria andUnitaccnumEqualTo(String value) {
			addCriterion("unitaccnum =", value, "unitaccnum");
			return (Criteria) this;
		}

		public Criteria andUnitaccnumNotEqualTo(String value) {
			addCriterion("unitaccnum <>", value, "unitaccnum");
			return (Criteria) this;
		}

		public Criteria andUnitaccnumGreaterThan(String value) {
			addCriterion("unitaccnum >", value, "unitaccnum");
			return (Criteria) this;
		}

		public Criteria andUnitaccnumGreaterThanOrEqualTo(String value) {
			addCriterion("unitaccnum >=", value, "unitaccnum");
			return (Criteria) this;
		}

		public Criteria andUnitaccnumLessThan(String value) {
			addCriterion("unitaccnum <", value, "unitaccnum");
			return (Criteria) this;
		}

		public Criteria andUnitaccnumLessThanOrEqualTo(String value) {
			addCriterion("unitaccnum <=", value, "unitaccnum");
			return (Criteria) this;
		}

		public Criteria andUnitaccnumLike(String value) {
			addCriterion("unitaccnum like", value, "unitaccnum");
			return (Criteria) this;
		}

		public Criteria andUnitaccnumNotLike(String value) {
			addCriterion("unitaccnum not like", value, "unitaccnum");
			return (Criteria) this;
		}

		public Criteria andUnitaccnumIn(List<String> values) {
			addCriterion("unitaccnum in", values, "unitaccnum");
			return (Criteria) this;
		}

		public Criteria andUnitaccnumNotIn(List<String> values) {
			addCriterion("unitaccnum not in", values, "unitaccnum");
			return (Criteria) this;
		}

		public Criteria andUnitaccnumBetween(String value1, String value2) {
			addCriterion("unitaccnum between", value1, value2, "unitaccnum");
			return (Criteria) this;
		}

		public Criteria andUnitaccnumNotBetween(String value1, String value2) {
			addCriterion("unitaccnum not between", value1, value2, "unitaccnum");
			return (Criteria) this;
		}

		public Criteria andUnitaccnameIsNull() {
			addCriterion("unitaccname is null");
			return (Criteria) this;
		}

		public Criteria andUnitaccnameIsNotNull() {
			addCriterion("unitaccname is not null");
			return (Criteria) this;
		}

		public Criteria andUnitaccnameEqualTo(String value) {
			addCriterion("unitaccname =", value, "unitaccname");
			return (Criteria) this;
		}

		public Criteria andUnitaccnameNotEqualTo(String value) {
			addCriterion("unitaccname <>", value, "unitaccname");
			return (Criteria) this;
		}

		public Criteria andUnitaccnameGreaterThan(String value) {
			addCriterion("unitaccname >", value, "unitaccname");
			return (Criteria) this;
		}

		public Criteria andUnitaccnameGreaterThanOrEqualTo(String value) {
			addCriterion("unitaccname >=", value, "unitaccname");
			return (Criteria) this;
		}

		public Criteria andUnitaccnameLessThan(String value) {
			addCriterion("unitaccname <", value, "unitaccname");
			return (Criteria) this;
		}

		public Criteria andUnitaccnameLessThanOrEqualTo(String value) {
			addCriterion("unitaccname <=", value, "unitaccname");
			return (Criteria) this;
		}

		public Criteria andUnitaccnameLike(String value) {
			addCriterion("unitaccname like", value, "unitaccname");
			return (Criteria) this;
		}

		public Criteria andUnitaccnameNotLike(String value) {
			addCriterion("unitaccname not like", value, "unitaccname");
			return (Criteria) this;
		}

		public Criteria andUnitaccnameIn(List<String> values) {
			addCriterion("unitaccname in", values, "unitaccname");
			return (Criteria) this;
		}

		public Criteria andUnitaccnameNotIn(List<String> values) {
			addCriterion("unitaccname not in", values, "unitaccname");
			return (Criteria) this;
		}

		public Criteria andUnitaccnameBetween(String value1, String value2) {
			addCriterion("unitaccname between", value1, value2, "unitaccname");
			return (Criteria) this;
		}

		public Criteria andUnitaccnameNotBetween(String value1, String value2) {
			addCriterion("unitaccname not between", value1, value2, "unitaccname");
			return (Criteria) this;
		}

		public Criteria andOrgcodeIsNull() {
			addCriterion("orgcode is null");
			return (Criteria) this;
		}

		public Criteria andOrgcodeIsNotNull() {
			addCriterion("orgcode is not null");
			return (Criteria) this;
		}

		public Criteria andOrgcodeEqualTo(String value) {
			addCriterion("orgcode =", value, "orgcode");
			return (Criteria) this;
		}

		public Criteria andOrgcodeNotEqualTo(String value) {
			addCriterion("orgcode <>", value, "orgcode");
			return (Criteria) this;
		}

		public Criteria andOrgcodeGreaterThan(String value) {
			addCriterion("orgcode >", value, "orgcode");
			return (Criteria) this;
		}

		public Criteria andOrgcodeGreaterThanOrEqualTo(String value) {
			addCriterion("orgcode >=", value, "orgcode");
			return (Criteria) this;
		}

		public Criteria andOrgcodeLessThan(String value) {
			addCriterion("orgcode <", value, "orgcode");
			return (Criteria) this;
		}

		public Criteria andOrgcodeLessThanOrEqualTo(String value) {
			addCriterion("orgcode <=", value, "orgcode");
			return (Criteria) this;
		}

		public Criteria andOrgcodeLike(String value) {
			addCriterion("orgcode like", value, "orgcode");
			return (Criteria) this;
		}

		public Criteria andOrgcodeNotLike(String value) {
			addCriterion("orgcode not like", value, "orgcode");
			return (Criteria) this;
		}

		public Criteria andOrgcodeIn(List<String> values) {
			addCriterion("orgcode in", values, "orgcode");
			return (Criteria) this;
		}

		public Criteria andOrgcodeNotIn(List<String> values) {
			addCriterion("orgcode not in", values, "orgcode");
			return (Criteria) this;
		}

		public Criteria andOrgcodeBetween(String value1, String value2) {
			addCriterion("orgcode between", value1, value2, "orgcode");
			return (Criteria) this;
		}

		public Criteria andOrgcodeNotBetween(String value1, String value2) {
			addCriterion("orgcode not between", value1, value2, "orgcode");
			return (Criteria) this;
		}

		public Criteria andUnitcharIsNull() {
			addCriterion("unitchar is null");
			return (Criteria) this;
		}

		public Criteria andUnitcharIsNotNull() {
			addCriterion("unitchar is not null");
			return (Criteria) this;
		}

		public Criteria andUnitcharEqualTo(String value) {
			addCriterion("unitchar =", value, "unitchar");
			return (Criteria) this;
		}

		public Criteria andUnitcharNotEqualTo(String value) {
			addCriterion("unitchar <>", value, "unitchar");
			return (Criteria) this;
		}

		public Criteria andUnitcharGreaterThan(String value) {
			addCriterion("unitchar >", value, "unitchar");
			return (Criteria) this;
		}

		public Criteria andUnitcharGreaterThanOrEqualTo(String value) {
			addCriterion("unitchar >=", value, "unitchar");
			return (Criteria) this;
		}

		public Criteria andUnitcharLessThan(String value) {
			addCriterion("unitchar <", value, "unitchar");
			return (Criteria) this;
		}

		public Criteria andUnitcharLessThanOrEqualTo(String value) {
			addCriterion("unitchar <=", value, "unitchar");
			return (Criteria) this;
		}

		public Criteria andUnitcharLike(String value) {
			addCriterion("unitchar like", value, "unitchar");
			return (Criteria) this;
		}

		public Criteria andUnitcharNotLike(String value) {
			addCriterion("unitchar not like", value, "unitchar");
			return (Criteria) this;
		}

		public Criteria andUnitcharIn(List<String> values) {
			addCriterion("unitchar in", values, "unitchar");
			return (Criteria) this;
		}

		public Criteria andUnitcharNotIn(List<String> values) {
			addCriterion("unitchar not in", values, "unitchar");
			return (Criteria) this;
		}

		public Criteria andUnitcharBetween(String value1, String value2) {
			addCriterion("unitchar between", value1, value2, "unitchar");
			return (Criteria) this;
		}

		public Criteria andUnitcharNotBetween(String value1, String value2) {
			addCriterion("unitchar not between", value1, value2, "unitchar");
			return (Criteria) this;
		}

		public Criteria andUnitkindIsNull() {
			addCriterion("unitkind is null");
			return (Criteria) this;
		}

		public Criteria andUnitkindIsNotNull() {
			addCriterion("unitkind is not null");
			return (Criteria) this;
		}

		public Criteria andUnitkindEqualTo(String value) {
			addCriterion("unitkind =", value, "unitkind");
			return (Criteria) this;
		}

		public Criteria andUnitkindNotEqualTo(String value) {
			addCriterion("unitkind <>", value, "unitkind");
			return (Criteria) this;
		}

		public Criteria andUnitkindGreaterThan(String value) {
			addCriterion("unitkind >", value, "unitkind");
			return (Criteria) this;
		}

		public Criteria andUnitkindGreaterThanOrEqualTo(String value) {
			addCriterion("unitkind >=", value, "unitkind");
			return (Criteria) this;
		}

		public Criteria andUnitkindLessThan(String value) {
			addCriterion("unitkind <", value, "unitkind");
			return (Criteria) this;
		}

		public Criteria andUnitkindLessThanOrEqualTo(String value) {
			addCriterion("unitkind <=", value, "unitkind");
			return (Criteria) this;
		}

		public Criteria andUnitkindLike(String value) {
			addCriterion("unitkind like", value, "unitkind");
			return (Criteria) this;
		}

		public Criteria andUnitkindNotLike(String value) {
			addCriterion("unitkind not like", value, "unitkind");
			return (Criteria) this;
		}

		public Criteria andUnitkindIn(List<String> values) {
			addCriterion("unitkind in", values, "unitkind");
			return (Criteria) this;
		}

		public Criteria andUnitkindNotIn(List<String> values) {
			addCriterion("unitkind not in", values, "unitkind");
			return (Criteria) this;
		}

		public Criteria andUnitkindBetween(String value1, String value2) {
			addCriterion("unitkind between", value1, value2, "unitkind");
			return (Criteria) this;
		}

		public Criteria andUnitkindNotBetween(String value1, String value2) {
			addCriterion("unitkind not between", value1, value2, "unitkind");
			return (Criteria) this;
		}

		public Criteria andSalarydateIsNull() {
			addCriterion("salarydate is null");
			return (Criteria) this;
		}

		public Criteria andSalarydateIsNotNull() {
			addCriterion("salarydate is not null");
			return (Criteria) this;
		}

		public Criteria andSalarydateEqualTo(String value) {
			addCriterion("salarydate =", value, "salarydate");
			return (Criteria) this;
		}

		public Criteria andSalarydateNotEqualTo(String value) {
			addCriterion("salarydate <>", value, "salarydate");
			return (Criteria) this;
		}

		public Criteria andSalarydateGreaterThan(String value) {
			addCriterion("salarydate >", value, "salarydate");
			return (Criteria) this;
		}

		public Criteria andSalarydateGreaterThanOrEqualTo(String value) {
			addCriterion("salarydate >=", value, "salarydate");
			return (Criteria) this;
		}

		public Criteria andSalarydateLessThan(String value) {
			addCriterion("salarydate <", value, "salarydate");
			return (Criteria) this;
		}

		public Criteria andSalarydateLessThanOrEqualTo(String value) {
			addCriterion("salarydate <=", value, "salarydate");
			return (Criteria) this;
		}

		public Criteria andSalarydateLike(String value) {
			addCriterion("salarydate like", value, "salarydate");
			return (Criteria) this;
		}

		public Criteria andSalarydateNotLike(String value) {
			addCriterion("salarydate not like", value, "salarydate");
			return (Criteria) this;
		}

		public Criteria andSalarydateIn(List<String> values) {
			addCriterion("salarydate in", values, "salarydate");
			return (Criteria) this;
		}

		public Criteria andSalarydateNotIn(List<String> values) {
			addCriterion("salarydate not in", values, "salarydate");
			return (Criteria) this;
		}

		public Criteria andSalarydateBetween(String value1, String value2) {
			addCriterion("salarydate between", value1, value2, "salarydate");
			return (Criteria) this;
		}

		public Criteria andSalarydateNotBetween(String value1, String value2) {
			addCriterion("salarydate not between", value1, value2, "salarydate");
			return (Criteria) this;
		}

		public Criteria andUnitphoneIsNull() {
			addCriterion("unitphone is null");
			return (Criteria) this;
		}

		public Criteria andUnitphoneIsNotNull() {
			addCriterion("unitphone is not null");
			return (Criteria) this;
		}

		public Criteria andUnitphoneEqualTo(String value) {
			addCriterion("unitphone =", value, "unitphone");
			return (Criteria) this;
		}

		public Criteria andUnitphoneNotEqualTo(String value) {
			addCriterion("unitphone <>", value, "unitphone");
			return (Criteria) this;
		}

		public Criteria andUnitphoneGreaterThan(String value) {
			addCriterion("unitphone >", value, "unitphone");
			return (Criteria) this;
		}

		public Criteria andUnitphoneGreaterThanOrEqualTo(String value) {
			addCriterion("unitphone >=", value, "unitphone");
			return (Criteria) this;
		}

		public Criteria andUnitphoneLessThan(String value) {
			addCriterion("unitphone <", value, "unitphone");
			return (Criteria) this;
		}

		public Criteria andUnitphoneLessThanOrEqualTo(String value) {
			addCriterion("unitphone <=", value, "unitphone");
			return (Criteria) this;
		}

		public Criteria andUnitphoneLike(String value) {
			addCriterion("unitphone like", value, "unitphone");
			return (Criteria) this;
		}

		public Criteria andUnitphoneNotLike(String value) {
			addCriterion("unitphone not like", value, "unitphone");
			return (Criteria) this;
		}

		public Criteria andUnitphoneIn(List<String> values) {
			addCriterion("unitphone in", values, "unitphone");
			return (Criteria) this;
		}

		public Criteria andUnitphoneNotIn(List<String> values) {
			addCriterion("unitphone not in", values, "unitphone");
			return (Criteria) this;
		}

		public Criteria andUnitphoneBetween(String value1, String value2) {
			addCriterion("unitphone between", value1, value2, "unitphone");
			return (Criteria) this;
		}

		public Criteria andUnitphoneNotBetween(String value1, String value2) {
			addCriterion("unitphone not between", value1, value2, "unitphone");
			return (Criteria) this;
		}

		public Criteria andUnitlinkmanIsNull() {
			addCriterion("unitlinkman is null");
			return (Criteria) this;
		}

		public Criteria andUnitlinkmanIsNotNull() {
			addCriterion("unitlinkman is not null");
			return (Criteria) this;
		}

		public Criteria andUnitlinkmanEqualTo(String value) {
			addCriterion("unitlinkman =", value, "unitlinkman");
			return (Criteria) this;
		}

		public Criteria andUnitlinkmanNotEqualTo(String value) {
			addCriterion("unitlinkman <>", value, "unitlinkman");
			return (Criteria) this;
		}

		public Criteria andUnitlinkmanGreaterThan(String value) {
			addCriterion("unitlinkman >", value, "unitlinkman");
			return (Criteria) this;
		}

		public Criteria andUnitlinkmanGreaterThanOrEqualTo(String value) {
			addCriterion("unitlinkman >=", value, "unitlinkman");
			return (Criteria) this;
		}

		public Criteria andUnitlinkmanLessThan(String value) {
			addCriterion("unitlinkman <", value, "unitlinkman");
			return (Criteria) this;
		}

		public Criteria andUnitlinkmanLessThanOrEqualTo(String value) {
			addCriterion("unitlinkman <=", value, "unitlinkman");
			return (Criteria) this;
		}

		public Criteria andUnitlinkmanLike(String value) {
			addCriterion("unitlinkman like", value, "unitlinkman");
			return (Criteria) this;
		}

		public Criteria andUnitlinkmanNotLike(String value) {
			addCriterion("unitlinkman not like", value, "unitlinkman");
			return (Criteria) this;
		}

		public Criteria andUnitlinkmanIn(List<String> values) {
			addCriterion("unitlinkman in", values, "unitlinkman");
			return (Criteria) this;
		}

		public Criteria andUnitlinkmanNotIn(List<String> values) {
			addCriterion("unitlinkman not in", values, "unitlinkman");
			return (Criteria) this;
		}

		public Criteria andUnitlinkmanBetween(String value1, String value2) {
			addCriterion("unitlinkman between", value1, value2, "unitlinkman");
			return (Criteria) this;
		}

		public Criteria andUnitlinkmanNotBetween(String value1, String value2) {
			addCriterion("unitlinkman not between", value1, value2, "unitlinkman");
			return (Criteria) this;
		}

		public Criteria andUnitagentpapnoIsNull() {
			addCriterion("unitagentpapno is null");
			return (Criteria) this;
		}

		public Criteria andUnitagentpapnoIsNotNull() {
			addCriterion("unitagentpapno is not null");
			return (Criteria) this;
		}

		public Criteria andUnitagentpapnoEqualTo(String value) {
			addCriterion("unitagentpapno =", value, "unitagentpapno");
			return (Criteria) this;
		}

		public Criteria andUnitagentpapnoNotEqualTo(String value) {
			addCriterion("unitagentpapno <>", value, "unitagentpapno");
			return (Criteria) this;
		}

		public Criteria andUnitagentpapnoGreaterThan(String value) {
			addCriterion("unitagentpapno >", value, "unitagentpapno");
			return (Criteria) this;
		}

		public Criteria andUnitagentpapnoGreaterThanOrEqualTo(String value) {
			addCriterion("unitagentpapno >=", value, "unitagentpapno");
			return (Criteria) this;
		}

		public Criteria andUnitagentpapnoLessThan(String value) {
			addCriterion("unitagentpapno <", value, "unitagentpapno");
			return (Criteria) this;
		}

		public Criteria andUnitagentpapnoLessThanOrEqualTo(String value) {
			addCriterion("unitagentpapno <=", value, "unitagentpapno");
			return (Criteria) this;
		}

		public Criteria andUnitagentpapnoLike(String value) {
			addCriterion("unitagentpapno like", value, "unitagentpapno");
			return (Criteria) this;
		}

		public Criteria andUnitagentpapnoNotLike(String value) {
			addCriterion("unitagentpapno not like", value, "unitagentpapno");
			return (Criteria) this;
		}

		public Criteria andUnitagentpapnoIn(List<String> values) {
			addCriterion("unitagentpapno in", values, "unitagentpapno");
			return (Criteria) this;
		}

		public Criteria andUnitagentpapnoNotIn(List<String> values) {
			addCriterion("unitagentpapno not in", values, "unitagentpapno");
			return (Criteria) this;
		}

		public Criteria andUnitagentpapnoBetween(String value1, String value2) {
			addCriterion("unitagentpapno between", value1, value2, "unitagentpapno");
			return (Criteria) this;
		}

		public Criteria andUnitagentpapnoNotBetween(String value1, String value2) {
			addCriterion("unitagentpapno not between", value1, value2, "unitagentpapno");
			return (Criteria) this;
		}

		public Criteria andAccstateIsNull() {
			addCriterion("accstate is null");
			return (Criteria) this;
		}

		public Criteria andAccstateIsNotNull() {
			addCriterion("accstate is not null");
			return (Criteria) this;
		}

		public Criteria andAccstateEqualTo(Integer value) {
			addCriterion("accstate =", value, "accstate");
			return (Criteria) this;
		}

		public Criteria andAccstateNotEqualTo(Integer value) {
			addCriterion("accstate <>", value, "accstate");
			return (Criteria) this;
		}

		public Criteria andAccstateGreaterThan(Integer value) {
			addCriterion("accstate >", value, "accstate");
			return (Criteria) this;
		}

		public Criteria andAccstateGreaterThanOrEqualTo(Integer value) {
			addCriterion("accstate >=", value, "accstate");
			return (Criteria) this;
		}

		public Criteria andAccstateLessThan(Integer value) {
			addCriterion("accstate <", value, "accstate");
			return (Criteria) this;
		}

		public Criteria andAccstateLessThanOrEqualTo(Integer value) {
			addCriterion("accstate <=", value, "accstate");
			return (Criteria) this;
		}

		public Criteria andAccstateIn(List<Integer> values) {
			addCriterion("accstate in", values, "accstate");
			return (Criteria) this;
		}

		public Criteria andAccstateNotIn(List<Integer> values) {
			addCriterion("accstate not in", values, "accstate");
			return (Criteria) this;
		}

		public Criteria andAccstateBetween(Integer value1, Integer value2) {
			addCriterion("accstate between", value1, value2, "accstate");
			return (Criteria) this;
		}

		public Criteria andAccstateNotBetween(Integer value1, Integer value2) {
			addCriterion("accstate not between", value1, value2, "accstate");
			return (Criteria) this;
		}

		public Criteria andBalanceIsNull() {
			addCriterion("balance is null");
			return (Criteria) this;
		}

		public Criteria andBalanceIsNotNull() {
			addCriterion("balance is not null");
			return (Criteria) this;
		}

		public Criteria andBalanceEqualTo(BigDecimal value) {
			addCriterion("balance =", value, "balance");
			return (Criteria) this;
		}

		public Criteria andBalanceNotEqualTo(BigDecimal value) {
			addCriterion("balance <>", value, "balance");
			return (Criteria) this;
		}

		public Criteria andBalanceGreaterThan(BigDecimal value) {
			addCriterion("balance >", value, "balance");
			return (Criteria) this;
		}

		public Criteria andBalanceGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("balance >=", value, "balance");
			return (Criteria) this;
		}

		public Criteria andBalanceLessThan(BigDecimal value) {
			addCriterion("balance <", value, "balance");
			return (Criteria) this;
		}

		public Criteria andBalanceLessThanOrEqualTo(BigDecimal value) {
			addCriterion("balance <=", value, "balance");
			return (Criteria) this;
		}

		public Criteria andBalanceIn(List<BigDecimal> values) {
			addCriterion("balance in", values, "balance");
			return (Criteria) this;
		}

		public Criteria andBalanceNotIn(List<BigDecimal> values) {
			addCriterion("balance not in", values, "balance");
			return (Criteria) this;
		}

		public Criteria andBalanceBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("balance between", value1, value2, "balance");
			return (Criteria) this;
		}

		public Criteria andBalanceNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("balance not between", value1, value2, "balance");
			return (Criteria) this;
		}

		public Criteria andBasenumberIsNull() {
			addCriterion("basenumber is null");
			return (Criteria) this;
		}

		public Criteria andBasenumberIsNotNull() {
			addCriterion("basenumber is not null");
			return (Criteria) this;
		}

		public Criteria andBasenumberEqualTo(BigDecimal value) {
			addCriterion("basenumber =", value, "basenumber");
			return (Criteria) this;
		}

		public Criteria andBasenumberNotEqualTo(BigDecimal value) {
			addCriterion("basenumber <>", value, "basenumber");
			return (Criteria) this;
		}

		public Criteria andBasenumberGreaterThan(BigDecimal value) {
			addCriterion("basenumber >", value, "basenumber");
			return (Criteria) this;
		}

		public Criteria andBasenumberGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("basenumber >=", value, "basenumber");
			return (Criteria) this;
		}

		public Criteria andBasenumberLessThan(BigDecimal value) {
			addCriterion("basenumber <", value, "basenumber");
			return (Criteria) this;
		}

		public Criteria andBasenumberLessThanOrEqualTo(BigDecimal value) {
			addCriterion("basenumber <=", value, "basenumber");
			return (Criteria) this;
		}

		public Criteria andBasenumberIn(List<BigDecimal> values) {
			addCriterion("basenumber in", values, "basenumber");
			return (Criteria) this;
		}

		public Criteria andBasenumberNotIn(List<BigDecimal> values) {
			addCriterion("basenumber not in", values, "basenumber");
			return (Criteria) this;
		}

		public Criteria andBasenumberBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("basenumber between", value1, value2, "basenumber");
			return (Criteria) this;
		}

		public Criteria andBasenumberNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("basenumber not between", value1, value2, "basenumber");
			return (Criteria) this;
		}

		public Criteria andUnitpropIsNull() {
			addCriterion("unitprop is null");
			return (Criteria) this;
		}

		public Criteria andUnitpropIsNotNull() {
			addCriterion("unitprop is not null");
			return (Criteria) this;
		}

		public Criteria andUnitpropEqualTo(BigDecimal value) {
			addCriterion("unitprop =", value, "unitprop");
			return (Criteria) this;
		}

		public Criteria andUnitpropNotEqualTo(BigDecimal value) {
			addCriterion("unitprop <>", value, "unitprop");
			return (Criteria) this;
		}

		public Criteria andUnitpropGreaterThan(BigDecimal value) {
			addCriterion("unitprop >", value, "unitprop");
			return (Criteria) this;
		}

		public Criteria andUnitpropGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("unitprop >=", value, "unitprop");
			return (Criteria) this;
		}

		public Criteria andUnitpropLessThan(BigDecimal value) {
			addCriterion("unitprop <", value, "unitprop");
			return (Criteria) this;
		}

		public Criteria andUnitpropLessThanOrEqualTo(BigDecimal value) {
			addCriterion("unitprop <=", value, "unitprop");
			return (Criteria) this;
		}

		public Criteria andUnitpropIn(List<BigDecimal> values) {
			addCriterion("unitprop in", values, "unitprop");
			return (Criteria) this;
		}

		public Criteria andUnitpropNotIn(List<BigDecimal> values) {
			addCriterion("unitprop not in", values, "unitprop");
			return (Criteria) this;
		}

		public Criteria andUnitpropBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("unitprop between", value1, value2, "unitprop");
			return (Criteria) this;
		}

		public Criteria andUnitpropNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("unitprop not between", value1, value2, "unitprop");
			return (Criteria) this;
		}

		public Criteria andPerpropIsNull() {
			addCriterion("perprop is null");
			return (Criteria) this;
		}

		public Criteria andPerpropIsNotNull() {
			addCriterion("perprop is not null");
			return (Criteria) this;
		}

		public Criteria andPerpropEqualTo(BigDecimal value) {
			addCriterion("perprop =", value, "perprop");
			return (Criteria) this;
		}

		public Criteria andPerpropNotEqualTo(BigDecimal value) {
			addCriterion("perprop <>", value, "perprop");
			return (Criteria) this;
		}

		public Criteria andPerpropGreaterThan(BigDecimal value) {
			addCriterion("perprop >", value, "perprop");
			return (Criteria) this;
		}

		public Criteria andPerpropGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("perprop >=", value, "perprop");
			return (Criteria) this;
		}

		public Criteria andPerpropLessThan(BigDecimal value) {
			addCriterion("perprop <", value, "perprop");
			return (Criteria) this;
		}

		public Criteria andPerpropLessThanOrEqualTo(BigDecimal value) {
			addCriterion("perprop <=", value, "perprop");
			return (Criteria) this;
		}

		public Criteria andPerpropIn(List<BigDecimal> values) {
			addCriterion("perprop in", values, "perprop");
			return (Criteria) this;
		}

		public Criteria andPerpropNotIn(List<BigDecimal> values) {
			addCriterion("perprop not in", values, "perprop");
			return (Criteria) this;
		}

		public Criteria andPerpropBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("perprop between", value1, value2, "perprop");
			return (Criteria) this;
		}

		public Criteria andPerpropNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("perprop not between", value1, value2, "perprop");
			return (Criteria) this;
		}

		public Criteria andUnitpaysumIsNull() {
			addCriterion("unitpaysum is null");
			return (Criteria) this;
		}

		public Criteria andUnitpaysumIsNotNull() {
			addCriterion("unitpaysum is not null");
			return (Criteria) this;
		}

		public Criteria andUnitpaysumEqualTo(BigDecimal value) {
			addCriterion("unitpaysum =", value, "unitpaysum");
			return (Criteria) this;
		}

		public Criteria andUnitpaysumNotEqualTo(BigDecimal value) {
			addCriterion("unitpaysum <>", value, "unitpaysum");
			return (Criteria) this;
		}

		public Criteria andUnitpaysumGreaterThan(BigDecimal value) {
			addCriterion("unitpaysum >", value, "unitpaysum");
			return (Criteria) this;
		}

		public Criteria andUnitpaysumGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("unitpaysum >=", value, "unitpaysum");
			return (Criteria) this;
		}

		public Criteria andUnitpaysumLessThan(BigDecimal value) {
			addCriterion("unitpaysum <", value, "unitpaysum");
			return (Criteria) this;
		}

		public Criteria andUnitpaysumLessThanOrEqualTo(BigDecimal value) {
			addCriterion("unitpaysum <=", value, "unitpaysum");
			return (Criteria) this;
		}

		public Criteria andUnitpaysumIn(List<BigDecimal> values) {
			addCriterion("unitpaysum in", values, "unitpaysum");
			return (Criteria) this;
		}

		public Criteria andUnitpaysumNotIn(List<BigDecimal> values) {
			addCriterion("unitpaysum not in", values, "unitpaysum");
			return (Criteria) this;
		}

		public Criteria andUnitpaysumBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("unitpaysum between", value1, value2, "unitpaysum");
			return (Criteria) this;
		}

		public Criteria andUnitpaysumNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("unitpaysum not between", value1, value2, "unitpaysum");
			return (Criteria) this;
		}

		public Criteria andPerpaysumIsNull() {
			addCriterion("perpaysum is null");
			return (Criteria) this;
		}

		public Criteria andPerpaysumIsNotNull() {
			addCriterion("perpaysum is not null");
			return (Criteria) this;
		}

		public Criteria andPerpaysumEqualTo(BigDecimal value) {
			addCriterion("perpaysum =", value, "perpaysum");
			return (Criteria) this;
		}

		public Criteria andPerpaysumNotEqualTo(BigDecimal value) {
			addCriterion("perpaysum <>", value, "perpaysum");
			return (Criteria) this;
		}

		public Criteria andPerpaysumGreaterThan(BigDecimal value) {
			addCriterion("perpaysum >", value, "perpaysum");
			return (Criteria) this;
		}

		public Criteria andPerpaysumGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("perpaysum >=", value, "perpaysum");
			return (Criteria) this;
		}

		public Criteria andPerpaysumLessThan(BigDecimal value) {
			addCriterion("perpaysum <", value, "perpaysum");
			return (Criteria) this;
		}

		public Criteria andPerpaysumLessThanOrEqualTo(BigDecimal value) {
			addCriterion("perpaysum <=", value, "perpaysum");
			return (Criteria) this;
		}

		public Criteria andPerpaysumIn(List<BigDecimal> values) {
			addCriterion("perpaysum in", values, "perpaysum");
			return (Criteria) this;
		}

		public Criteria andPerpaysumNotIn(List<BigDecimal> values) {
			addCriterion("perpaysum not in", values, "perpaysum");
			return (Criteria) this;
		}

		public Criteria andPerpaysumBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("perpaysum between", value1, value2, "perpaysum");
			return (Criteria) this;
		}

		public Criteria andPerpaysumNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("perpaysum not between", value1, value2, "perpaysum");
			return (Criteria) this;
		}

		public Criteria andPersnumIsNull() {
			addCriterion("persnum is null");
			return (Criteria) this;
		}

		public Criteria andPersnumIsNotNull() {
			addCriterion("persnum is not null");
			return (Criteria) this;
		}

		public Criteria andPersnumEqualTo(Integer value) {
			addCriterion("persnum =", value, "persnum");
			return (Criteria) this;
		}

		public Criteria andPersnumNotEqualTo(Integer value) {
			addCriterion("persnum <>", value, "persnum");
			return (Criteria) this;
		}

		public Criteria andPersnumGreaterThan(Integer value) {
			addCriterion("persnum >", value, "persnum");
			return (Criteria) this;
		}

		public Criteria andPersnumGreaterThanOrEqualTo(Integer value) {
			addCriterion("persnum >=", value, "persnum");
			return (Criteria) this;
		}

		public Criteria andPersnumLessThan(Integer value) {
			addCriterion("persnum <", value, "persnum");
			return (Criteria) this;
		}

		public Criteria andPersnumLessThanOrEqualTo(Integer value) {
			addCriterion("persnum <=", value, "persnum");
			return (Criteria) this;
		}

		public Criteria andPersnumIn(List<Integer> values) {
			addCriterion("persnum in", values, "persnum");
			return (Criteria) this;
		}

		public Criteria andPersnumNotIn(List<Integer> values) {
			addCriterion("persnum not in", values, "persnum");
			return (Criteria) this;
		}

		public Criteria andPersnumBetween(Integer value1, Integer value2) {
			addCriterion("persnum between", value1, value2, "persnum");
			return (Criteria) this;
		}

		public Criteria andPersnumNotBetween(Integer value1, Integer value2) {
			addCriterion("persnum not between", value1, value2, "persnum");
			return (Criteria) this;
		}

		public Criteria andLastpaydateIsNull() {
			addCriterion("lastpaydate is null");
			return (Criteria) this;
		}

		public Criteria andLastpaydateIsNotNull() {
			addCriterion("lastpaydate is not null");
			return (Criteria) this;
		}

		public Criteria andLastpaydateEqualTo(Date value) {
			addCriterionForJDBCDate("lastpaydate =", value, "lastpaydate");
			return (Criteria) this;
		}

		public Criteria andLastpaydateNotEqualTo(Date value) {
			addCriterionForJDBCDate("lastpaydate <>", value, "lastpaydate");
			return (Criteria) this;
		}

		public Criteria andLastpaydateGreaterThan(Date value) {
			addCriterionForJDBCDate("lastpaydate >", value, "lastpaydate");
			return (Criteria) this;
		}

		public Criteria andLastpaydateGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("lastpaydate >=", value, "lastpaydate");
			return (Criteria) this;
		}

		public Criteria andLastpaydateLessThan(Date value) {
			addCriterionForJDBCDate("lastpaydate <", value, "lastpaydate");
			return (Criteria) this;
		}

		public Criteria andLastpaydateLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("lastpaydate <=", value, "lastpaydate");
			return (Criteria) this;
		}

		public Criteria andLastpaydateIn(List<Date> values) {
			addCriterionForJDBCDate("lastpaydate in", values, "lastpaydate");
			return (Criteria) this;
		}

		public Criteria andLastpaydateNotIn(List<Date> values) {
			addCriterionForJDBCDate("lastpaydate not in", values, "lastpaydate");
			return (Criteria) this;
		}

		public Criteria andLastpaydateBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("lastpaydate between", value1, value2, "lastpaydate");
			return (Criteria) this;
		}

		public Criteria andLastpaydateNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("lastpaydate not between", value1, value2, "lastpaydate");
			return (Criteria) this;
		}

		public Criteria andInstcodeIsNull() {
			addCriterion("instcode is null");
			return (Criteria) this;
		}

		public Criteria andInstcodeIsNotNull() {
			addCriterion("instcode is not null");
			return (Criteria) this;
		}

		public Criteria andInstcodeEqualTo(String value) {
			addCriterion("instcode =", value, "instcode");
			return (Criteria) this;
		}

		public Criteria andInstcodeNotEqualTo(String value) {
			addCriterion("instcode <>", value, "instcode");
			return (Criteria) this;
		}

		public Criteria andInstcodeGreaterThan(String value) {
			addCriterion("instcode >", value, "instcode");
			return (Criteria) this;
		}

		public Criteria andInstcodeGreaterThanOrEqualTo(String value) {
			addCriterion("instcode >=", value, "instcode");
			return (Criteria) this;
		}

		public Criteria andInstcodeLessThan(String value) {
			addCriterion("instcode <", value, "instcode");
			return (Criteria) this;
		}

		public Criteria andInstcodeLessThanOrEqualTo(String value) {
			addCriterion("instcode <=", value, "instcode");
			return (Criteria) this;
		}

		public Criteria andInstcodeLike(String value) {
			addCriterion("instcode like", value, "instcode");
			return (Criteria) this;
		}

		public Criteria andInstcodeNotLike(String value) {
			addCriterion("instcode not like", value, "instcode");
			return (Criteria) this;
		}

		public Criteria andInstcodeIn(List<String> values) {
			addCriterion("instcode in", values, "instcode");
			return (Criteria) this;
		}

		public Criteria andInstcodeNotIn(List<String> values) {
			addCriterion("instcode not in", values, "instcode");
			return (Criteria) this;
		}

		public Criteria andInstcodeBetween(String value1, String value2) {
			addCriterion("instcode between", value1, value2, "instcode");
			return (Criteria) this;
		}

		public Criteria andInstcodeNotBetween(String value1, String value2) {
			addCriterion("instcode not between", value1, value2, "instcode");
			return (Criteria) this;
		}

		public Criteria andOpIsNull() {
			addCriterion("op is null");
			return (Criteria) this;
		}

		public Criteria andOpIsNotNull() {
			addCriterion("op is not null");
			return (Criteria) this;
		}

		public Criteria andOpEqualTo(String value) {
			addCriterion("op =", value, "op");
			return (Criteria) this;
		}

		public Criteria andOpNotEqualTo(String value) {
			addCriterion("op <>", value, "op");
			return (Criteria) this;
		}

		public Criteria andOpGreaterThan(String value) {
			addCriterion("op >", value, "op");
			return (Criteria) this;
		}

		public Criteria andOpGreaterThanOrEqualTo(String value) {
			addCriterion("op >=", value, "op");
			return (Criteria) this;
		}

		public Criteria andOpLessThan(String value) {
			addCriterion("op <", value, "op");
			return (Criteria) this;
		}

		public Criteria andOpLessThanOrEqualTo(String value) {
			addCriterion("op <=", value, "op");
			return (Criteria) this;
		}

		public Criteria andOpLike(String value) {
			addCriterion("op like", value, "op");
			return (Criteria) this;
		}

		public Criteria andOpNotLike(String value) {
			addCriterion("op not like", value, "op");
			return (Criteria) this;
		}

		public Criteria andOpIn(List<String> values) {
			addCriterion("op in", values, "op");
			return (Criteria) this;
		}

		public Criteria andOpNotIn(List<String> values) {
			addCriterion("op not in", values, "op");
			return (Criteria) this;
		}

		public Criteria andOpBetween(String value1, String value2) {
			addCriterion("op between", value1, value2, "op");
			return (Criteria) this;
		}

		public Criteria andOpNotBetween(String value1, String value2) {
			addCriterion("op not between", value1, value2, "op");
			return (Criteria) this;
		}

		public Criteria andCreatedateIsNull() {
			addCriterion("createdate is null");
			return (Criteria) this;
		}

		public Criteria andCreatedateIsNotNull() {
			addCriterion("createdate is not null");
			return (Criteria) this;
		}

		public Criteria andCreatedateEqualTo(Date value) {
			addCriterionForJDBCDate("createdate =", value, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateNotEqualTo(Date value) {
			addCriterionForJDBCDate("createdate <>", value, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateGreaterThan(Date value) {
			addCriterionForJDBCDate("createdate >", value, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("createdate >=", value, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateLessThan(Date value) {
			addCriterionForJDBCDate("createdate <", value, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("createdate <=", value, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateIn(List<Date> values) {
			addCriterionForJDBCDate("createdate in", values, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateNotIn(List<Date> values) {
			addCriterionForJDBCDate("createdate not in", values, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("createdate between", value1, value2, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("createdate not between", value1, value2, "createdate");
			return (Criteria) this;
		}

		public Criteria andRemarkIsNull() {
			addCriterion("remark is null");
			return (Criteria) this;
		}

		public Criteria andRemarkIsNotNull() {
			addCriterion("remark is not null");
			return (Criteria) this;
		}

		public Criteria andRemarkEqualTo(String value) {
			addCriterion("remark =", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotEqualTo(String value) {
			addCriterion("remark <>", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkGreaterThan(String value) {
			addCriterion("remark >", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkGreaterThanOrEqualTo(String value) {
			addCriterion("remark >=", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLessThan(String value) {
			addCriterion("remark <", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLessThanOrEqualTo(String value) {
			addCriterion("remark <=", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLike(String value) {
			addCriterion("remark like", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotLike(String value) {
			addCriterion("remark not like", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkIn(List<String> values) {
			addCriterion("remark in", values, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotIn(List<String> values) {
			addCriterion("remark not in", values, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkBetween(String value1, String value2) {
			addCriterion("remark between", value1, value2, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotBetween(String value1, String value2) {
			addCriterion("remark not between", value1, value2, "remark");
			return (Criteria) this;
		}

		public Criteria andR1IsNull() {
			addCriterion("r1 is null");
			return (Criteria) this;
		}

		public Criteria andR1IsNotNull() {
			addCriterion("r1 is not null");
			return (Criteria) this;
		}

		public Criteria andR1EqualTo(String value) {
			addCriterion("r1 =", value, "r1");
			return (Criteria) this;
		}

		public Criteria andR1NotEqualTo(String value) {
			addCriterion("r1 <>", value, "r1");
			return (Criteria) this;
		}

		public Criteria andR1GreaterThan(String value) {
			addCriterion("r1 >", value, "r1");
			return (Criteria) this;
		}

		public Criteria andR1GreaterThanOrEqualTo(String value) {
			addCriterion("r1 >=", value, "r1");
			return (Criteria) this;
		}

		public Criteria andR1LessThan(String value) {
			addCriterion("r1 <", value, "r1");
			return (Criteria) this;
		}

		public Criteria andR1LessThanOrEqualTo(String value) {
			addCriterion("r1 <=", value, "r1");
			return (Criteria) this;
		}

		public Criteria andR1Like(String value) {
			addCriterion("r1 like", value, "r1");
			return (Criteria) this;
		}

		public Criteria andR1NotLike(String value) {
			addCriterion("r1 not like", value, "r1");
			return (Criteria) this;
		}

		public Criteria andR1In(List<String> values) {
			addCriterion("r1 in", values, "r1");
			return (Criteria) this;
		}

		public Criteria andR1NotIn(List<String> values) {
			addCriterion("r1 not in", values, "r1");
			return (Criteria) this;
		}

		public Criteria andR1Between(String value1, String value2) {
			addCriterion("r1 between", value1, value2, "r1");
			return (Criteria) this;
		}

		public Criteria andR1NotBetween(String value1, String value2) {
			addCriterion("r1 not between", value1, value2, "r1");
			return (Criteria) this;
		}

		public Criteria andR2IsNull() {
			addCriterion("r2 is null");
			return (Criteria) this;
		}

		public Criteria andR2IsNotNull() {
			addCriterion("r2 is not null");
			return (Criteria) this;
		}

		public Criteria andR2EqualTo(String value) {
			addCriterion("r2 =", value, "r2");
			return (Criteria) this;
		}

		public Criteria andR2NotEqualTo(String value) {
			addCriterion("r2 <>", value, "r2");
			return (Criteria) this;
		}

		public Criteria andR2GreaterThan(String value) {
			addCriterion("r2 >", value, "r2");
			return (Criteria) this;
		}

		public Criteria andR2GreaterThanOrEqualTo(String value) {
			addCriterion("r2 >=", value, "r2");
			return (Criteria) this;
		}

		public Criteria andR2LessThan(String value) {
			addCriterion("r2 <", value, "r2");
			return (Criteria) this;
		}

		public Criteria andR2LessThanOrEqualTo(String value) {
			addCriterion("r2 <=", value, "r2");
			return (Criteria) this;
		}

		public Criteria andR2Like(String value) {
			addCriterion("r2 like", value, "r2");
			return (Criteria) this;
		}

		public Criteria andR2NotLike(String value) {
			addCriterion("r2 not like", value, "r2");
			return (Criteria) this;
		}

		public Criteria andR2In(List<String> values) {
			addCriterion("r2 in", values, "r2");
			return (Criteria) this;
		}

		public Criteria andR2NotIn(List<String> values) {
			addCriterion("r2 not in", values, "r2");
			return (Criteria) this;
		}

		public Criteria andR2Between(String value1, String value2) {
			addCriterion("r2 between", value1, value2, "r2");
			return (Criteria) this;
		}

		public Criteria andR2NotBetween(String value1, String value2) {
			addCriterion("r2 not between", value1, value2, "r2");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table company
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table company
     *
     * @mbggenerated do_not_delete_during_merge Mon Jul 11 15:16:37 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}