package com.edu.ccut.pojo;

import java.util.Date;

public class Focus {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column focus.id
	 * @mbggenerated  Mon Jan 02 17:35:41 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column focus.focusto
	 * @mbggenerated  Mon Jan 02 17:35:41 CST 2017
	 */
	private Integer focusto;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column focus.focusfrom
	 * @mbggenerated  Mon Jan 02 17:35:41 CST 2017
	 */
	private Integer focusfrom;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column focus.focusflag
	 * @mbggenerated  Mon Jan 02 17:35:41 CST 2017
	 */
	private Integer focusflag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column focus.focusstate
	 * @mbggenerated  Mon Jan 02 17:35:41 CST 2017
	 */
	private Integer focusstate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column focus.createdate
	 * @mbggenerated  Mon Jan 02 17:35:41 CST 2017
	 */
	private Date createdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column focus.r1
	 * @mbggenerated  Mon Jan 02 17:35:41 CST 2017
	 */
	private String r1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column focus.r2
	 * @mbggenerated  Mon Jan 02 17:35:41 CST 2017
	 */
	private String r2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column focus.r3
	 * @mbggenerated  Mon Jan 02 17:35:41 CST 2017
	 */
	private String r3;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column focus.id
	 * @return  the value of focus.id
	 * @mbggenerated  Mon Jan 02 17:35:41 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column focus.id
	 * @param id  the value for focus.id
	 * @mbggenerated  Mon Jan 02 17:35:41 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column focus.focusto
	 * @return  the value of focus.focusto
	 * @mbggenerated  Mon Jan 02 17:35:41 CST 2017
	 */
	public Integer getFocusto() {
		return focusto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column focus.focusto
	 * @param focusto  the value for focus.focusto
	 * @mbggenerated  Mon Jan 02 17:35:41 CST 2017
	 */
	public void setFocusto(Integer focusto) {
		this.focusto = focusto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column focus.focusfrom
	 * @return  the value of focus.focusfrom
	 * @mbggenerated  Mon Jan 02 17:35:41 CST 2017
	 */
	public Integer getFocusfrom() {
		return focusfrom;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column focus.focusfrom
	 * @param focusfrom  the value for focus.focusfrom
	 * @mbggenerated  Mon Jan 02 17:35:41 CST 2017
	 */
	public void setFocusfrom(Integer focusfrom) {
		this.focusfrom = focusfrom;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column focus.focusflag
	 * @return  the value of focus.focusflag
	 * @mbggenerated  Mon Jan 02 17:35:41 CST 2017
	 */
	public Integer getFocusflag() {
		return focusflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column focus.focusflag
	 * @param focusflag  the value for focus.focusflag
	 * @mbggenerated  Mon Jan 02 17:35:41 CST 2017
	 */
	public void setFocusflag(Integer focusflag) {
		this.focusflag = focusflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column focus.focusstate
	 * @return  the value of focus.focusstate
	 * @mbggenerated  Mon Jan 02 17:35:41 CST 2017
	 */
	public Integer getFocusstate() {
		return focusstate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column focus.focusstate
	 * @param focusstate  the value for focus.focusstate
	 * @mbggenerated  Mon Jan 02 17:35:41 CST 2017
	 */
	public void setFocusstate(Integer focusstate) {
		this.focusstate = focusstate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column focus.createdate
	 * @return  the value of focus.createdate
	 * @mbggenerated  Mon Jan 02 17:35:41 CST 2017
	 */
	public Date getCreatedate() {
		return createdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column focus.createdate
	 * @param createdate  the value for focus.createdate
	 * @mbggenerated  Mon Jan 02 17:35:41 CST 2017
	 */
	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column focus.r1
	 * @return  the value of focus.r1
	 * @mbggenerated  Mon Jan 02 17:35:41 CST 2017
	 */
	public String getR1() {
		return r1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column focus.r1
	 * @param r1  the value for focus.r1
	 * @mbggenerated  Mon Jan 02 17:35:41 CST 2017
	 */
	public void setR1(String r1) {
		this.r1 = r1 == null ? null : r1.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column focus.r2
	 * @return  the value of focus.r2
	 * @mbggenerated  Mon Jan 02 17:35:41 CST 2017
	 */
	public String getR2() {
		return r2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column focus.r2
	 * @param r2  the value for focus.r2
	 * @mbggenerated  Mon Jan 02 17:35:41 CST 2017
	 */
	public void setR2(String r2) {
		this.r2 = r2 == null ? null : r2.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column focus.r3
	 * @return  the value of focus.r3
	 * @mbggenerated  Mon Jan 02 17:35:41 CST 2017
	 */
	public String getR3() {
		return r3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column focus.r3
	 * @param r3  the value for focus.r3
	 * @mbggenerated  Mon Jan 02 17:35:41 CST 2017
	 */
	public void setR3(String r3) {
		this.r3 = r3 == null ? null : r3.trim();
	}
}