package com.edu.ccut.pojo;

import java.util.Date;

public class Laud {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column laud.id
	 * @mbggenerated  Mon Jan 02 17:35:41 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column laud.laudfrom
	 * @mbggenerated  Mon Jan 02 17:35:41 CST 2017
	 */
	private Integer laudfrom;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column laud.laudto
	 * @mbggenerated  Mon Jan 02 17:35:41 CST 2017
	 */
	private Integer laudto;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column laud.state
	 * @mbggenerated  Mon Jan 02 17:35:41 CST 2017
	 */
	private Integer state;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column laud.lauddate
	 * @mbggenerated  Mon Jan 02 17:35:41 CST 2017
	 */
	private Date lauddate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column laud.laudflag
	 * @mbggenerated  Mon Jan 02 17:35:41 CST 2017
	 */
	private Integer laudflag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column laud.r1
	 * @mbggenerated  Mon Jan 02 17:35:41 CST 2017
	 */
	private String r1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column laud.r2
	 * @mbggenerated  Mon Jan 02 17:35:41 CST 2017
	 */
	private String r2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column laud.r3
	 * @mbggenerated  Mon Jan 02 17:35:41 CST 2017
	 */
	private String r3;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column laud.id
	 * @return  the value of laud.id
	 * @mbggenerated  Mon Jan 02 17:35:41 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column laud.id
	 * @param id  the value for laud.id
	 * @mbggenerated  Mon Jan 02 17:35:41 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column laud.laudfrom
	 * @return  the value of laud.laudfrom
	 * @mbggenerated  Mon Jan 02 17:35:41 CST 2017
	 */
	public Integer getLaudfrom() {
		return laudfrom;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column laud.laudfrom
	 * @param laudfrom  the value for laud.laudfrom
	 * @mbggenerated  Mon Jan 02 17:35:41 CST 2017
	 */
	public void setLaudfrom(Integer laudfrom) {
		this.laudfrom = laudfrom;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column laud.laudto
	 * @return  the value of laud.laudto
	 * @mbggenerated  Mon Jan 02 17:35:41 CST 2017
	 */
	public Integer getLaudto() {
		return laudto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column laud.laudto
	 * @param laudto  the value for laud.laudto
	 * @mbggenerated  Mon Jan 02 17:35:41 CST 2017
	 */
	public void setLaudto(Integer laudto) {
		this.laudto = laudto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column laud.state
	 * @return  the value of laud.state
	 * @mbggenerated  Mon Jan 02 17:35:41 CST 2017
	 */
	public Integer getState() {
		return state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column laud.state
	 * @param state  the value for laud.state
	 * @mbggenerated  Mon Jan 02 17:35:41 CST 2017
	 */
	public void setState(Integer state) {
		this.state = state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column laud.lauddate
	 * @return  the value of laud.lauddate
	 * @mbggenerated  Mon Jan 02 17:35:41 CST 2017
	 */
	public Date getLauddate() {
		return lauddate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column laud.lauddate
	 * @param lauddate  the value for laud.lauddate
	 * @mbggenerated  Mon Jan 02 17:35:41 CST 2017
	 */
	public void setLauddate(Date lauddate) {
		this.lauddate = lauddate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column laud.laudflag
	 * @return  the value of laud.laudflag
	 * @mbggenerated  Mon Jan 02 17:35:41 CST 2017
	 */
	public Integer getLaudflag() {
		return laudflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column laud.laudflag
	 * @param laudflag  the value for laud.laudflag
	 * @mbggenerated  Mon Jan 02 17:35:41 CST 2017
	 */
	public void setLaudflag(Integer laudflag) {
		this.laudflag = laudflag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column laud.r1
	 * @return  the value of laud.r1
	 * @mbggenerated  Mon Jan 02 17:35:41 CST 2017
	 */
	public String getR1() {
		return r1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column laud.r1
	 * @param r1  the value for laud.r1
	 * @mbggenerated  Mon Jan 02 17:35:41 CST 2017
	 */
	public void setR1(String r1) {
		this.r1 = r1 == null ? null : r1.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column laud.r2
	 * @return  the value of laud.r2
	 * @mbggenerated  Mon Jan 02 17:35:41 CST 2017
	 */
	public String getR2() {
		return r2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column laud.r2
	 * @param r2  the value for laud.r2
	 * @mbggenerated  Mon Jan 02 17:35:41 CST 2017
	 */
	public void setR2(String r2) {
		this.r2 = r2 == null ? null : r2.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column laud.r3
	 * @return  the value of laud.r3
	 * @mbggenerated  Mon Jan 02 17:35:41 CST 2017
	 */
	public String getR3() {
		return r3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column laud.r3
	 * @param r3  the value for laud.r3
	 * @mbggenerated  Mon Jan 02 17:35:41 CST 2017
	 */
	public void setR3(String r3) {
		this.r3 = r3 == null ? null : r3.trim();
	}
}