package com.edu.ccut.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class LaudExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table laud
     *
     * @mbggenerated Mon Jan 02 17:35:41 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table laud
     *
     * @mbggenerated Mon Jan 02 17:35:41 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table laud
     *
     * @mbggenerated Mon Jan 02 17:35:41 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table laud
     *
     * @mbggenerated Mon Jan 02 17:35:41 CST 2017
     */
    public LaudExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table laud
     *
     * @mbggenerated Mon Jan 02 17:35:41 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table laud
     *
     * @mbggenerated Mon Jan 02 17:35:41 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table laud
     *
     * @mbggenerated Mon Jan 02 17:35:41 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table laud
     *
     * @mbggenerated Mon Jan 02 17:35:41 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table laud
     *
     * @mbggenerated Mon Jan 02 17:35:41 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table laud
     *
     * @mbggenerated Mon Jan 02 17:35:41 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table laud
     *
     * @mbggenerated Mon Jan 02 17:35:41 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table laud
     *
     * @mbggenerated Mon Jan 02 17:35:41 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table laud
     *
     * @mbggenerated Mon Jan 02 17:35:41 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table laud
     *
     * @mbggenerated Mon Jan 02 17:35:41 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table laud
     *
     * @mbggenerated Mon Jan 02 17:35:41 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andLaudfromIsNull() {
            addCriterion("laudfrom is null");
            return (Criteria) this;
        }

        public Criteria andLaudfromIsNotNull() {
            addCriterion("laudfrom is not null");
            return (Criteria) this;
        }

        public Criteria andLaudfromEqualTo(Integer value) {
            addCriterion("laudfrom =", value, "laudfrom");
            return (Criteria) this;
        }

        public Criteria andLaudfromNotEqualTo(Integer value) {
            addCriterion("laudfrom <>", value, "laudfrom");
            return (Criteria) this;
        }

        public Criteria andLaudfromGreaterThan(Integer value) {
            addCriterion("laudfrom >", value, "laudfrom");
            return (Criteria) this;
        }

        public Criteria andLaudfromGreaterThanOrEqualTo(Integer value) {
            addCriterion("laudfrom >=", value, "laudfrom");
            return (Criteria) this;
        }

        public Criteria andLaudfromLessThan(Integer value) {
            addCriterion("laudfrom <", value, "laudfrom");
            return (Criteria) this;
        }

        public Criteria andLaudfromLessThanOrEqualTo(Integer value) {
            addCriterion("laudfrom <=", value, "laudfrom");
            return (Criteria) this;
        }

        public Criteria andLaudfromIn(List<Integer> values) {
            addCriterion("laudfrom in", values, "laudfrom");
            return (Criteria) this;
        }

        public Criteria andLaudfromNotIn(List<Integer> values) {
            addCriterion("laudfrom not in", values, "laudfrom");
            return (Criteria) this;
        }

        public Criteria andLaudfromBetween(Integer value1, Integer value2) {
            addCriterion("laudfrom between", value1, value2, "laudfrom");
            return (Criteria) this;
        }

        public Criteria andLaudfromNotBetween(Integer value1, Integer value2) {
            addCriterion("laudfrom not between", value1, value2, "laudfrom");
            return (Criteria) this;
        }

        public Criteria andLaudtoIsNull() {
            addCriterion("laudto is null");
            return (Criteria) this;
        }

        public Criteria andLaudtoIsNotNull() {
            addCriterion("laudto is not null");
            return (Criteria) this;
        }

        public Criteria andLaudtoEqualTo(Integer value) {
            addCriterion("laudto =", value, "laudto");
            return (Criteria) this;
        }

        public Criteria andLaudtoNotEqualTo(Integer value) {
            addCriterion("laudto <>", value, "laudto");
            return (Criteria) this;
        }

        public Criteria andLaudtoGreaterThan(Integer value) {
            addCriterion("laudto >", value, "laudto");
            return (Criteria) this;
        }

        public Criteria andLaudtoGreaterThanOrEqualTo(Integer value) {
            addCriterion("laudto >=", value, "laudto");
            return (Criteria) this;
        }

        public Criteria andLaudtoLessThan(Integer value) {
            addCriterion("laudto <", value, "laudto");
            return (Criteria) this;
        }

        public Criteria andLaudtoLessThanOrEqualTo(Integer value) {
            addCriterion("laudto <=", value, "laudto");
            return (Criteria) this;
        }

        public Criteria andLaudtoIn(List<Integer> values) {
            addCriterion("laudto in", values, "laudto");
            return (Criteria) this;
        }

        public Criteria andLaudtoNotIn(List<Integer> values) {
            addCriterion("laudto not in", values, "laudto");
            return (Criteria) this;
        }

        public Criteria andLaudtoBetween(Integer value1, Integer value2) {
            addCriterion("laudto between", value1, value2, "laudto");
            return (Criteria) this;
        }

        public Criteria andLaudtoNotBetween(Integer value1, Integer value2) {
            addCriterion("laudto not between", value1, value2, "laudto");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("state is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("state is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(Integer value) {
            addCriterion("state =", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(Integer value) {
            addCriterion("state <>", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(Integer value) {
            addCriterion("state >", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(Integer value) {
            addCriterion("state >=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThan(Integer value) {
            addCriterion("state <", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(Integer value) {
            addCriterion("state <=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateIn(List<Integer> values) {
            addCriterion("state in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<Integer> values) {
            addCriterion("state not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(Integer value1, Integer value2) {
            addCriterion("state between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(Integer value1, Integer value2) {
            addCriterion("state not between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andLauddateIsNull() {
            addCriterion("lauddate is null");
            return (Criteria) this;
        }

        public Criteria andLauddateIsNotNull() {
            addCriterion("lauddate is not null");
            return (Criteria) this;
        }

        public Criteria andLauddateEqualTo(Date value) {
            addCriterion("lauddate =", value, "lauddate");
            return (Criteria) this;
        }

        public Criteria andLauddateNotEqualTo(Date value) {
            addCriterion("lauddate <>", value, "lauddate");
            return (Criteria) this;
        }

        public Criteria andLauddateGreaterThan(Date value) {
            addCriterion("lauddate >", value, "lauddate");
            return (Criteria) this;
        }

        public Criteria andLauddateGreaterThanOrEqualTo(Date value) {
            addCriterion("lauddate >=", value, "lauddate");
            return (Criteria) this;
        }

        public Criteria andLauddateLessThan(Date value) {
            addCriterion("lauddate <", value, "lauddate");
            return (Criteria) this;
        }

        public Criteria andLauddateLessThanOrEqualTo(Date value) {
            addCriterion("lauddate <=", value, "lauddate");
            return (Criteria) this;
        }

        public Criteria andLauddateIn(List<Date> values) {
            addCriterion("lauddate in", values, "lauddate");
            return (Criteria) this;
        }

        public Criteria andLauddateNotIn(List<Date> values) {
            addCriterion("lauddate not in", values, "lauddate");
            return (Criteria) this;
        }

        public Criteria andLauddateBetween(Date value1, Date value2) {
            addCriterion("lauddate between", value1, value2, "lauddate");
            return (Criteria) this;
        }

        public Criteria andLauddateNotBetween(Date value1, Date value2) {
            addCriterion("lauddate not between", value1, value2, "lauddate");
            return (Criteria) this;
        }

        public Criteria andLaudflagIsNull() {
            addCriterion("laudflag is null");
            return (Criteria) this;
        }

        public Criteria andLaudflagIsNotNull() {
            addCriterion("laudflag is not null");
            return (Criteria) this;
        }

        public Criteria andLaudflagEqualTo(Integer value) {
            addCriterion("laudflag =", value, "laudflag");
            return (Criteria) this;
        }

        public Criteria andLaudflagNotEqualTo(Integer value) {
            addCriterion("laudflag <>", value, "laudflag");
            return (Criteria) this;
        }

        public Criteria andLaudflagGreaterThan(Integer value) {
            addCriterion("laudflag >", value, "laudflag");
            return (Criteria) this;
        }

        public Criteria andLaudflagGreaterThanOrEqualTo(Integer value) {
            addCriterion("laudflag >=", value, "laudflag");
            return (Criteria) this;
        }

        public Criteria andLaudflagLessThan(Integer value) {
            addCriterion("laudflag <", value, "laudflag");
            return (Criteria) this;
        }

        public Criteria andLaudflagLessThanOrEqualTo(Integer value) {
            addCriterion("laudflag <=", value, "laudflag");
            return (Criteria) this;
        }

        public Criteria andLaudflagIn(List<Integer> values) {
            addCriterion("laudflag in", values, "laudflag");
            return (Criteria) this;
        }

        public Criteria andLaudflagNotIn(List<Integer> values) {
            addCriterion("laudflag not in", values, "laudflag");
            return (Criteria) this;
        }

        public Criteria andLaudflagBetween(Integer value1, Integer value2) {
            addCriterion("laudflag between", value1, value2, "laudflag");
            return (Criteria) this;
        }

        public Criteria andLaudflagNotBetween(Integer value1, Integer value2) {
            addCriterion("laudflag not between", value1, value2, "laudflag");
            return (Criteria) this;
        }

        public Criteria andR1IsNull() {
            addCriterion("r1 is null");
            return (Criteria) this;
        }

        public Criteria andR1IsNotNull() {
            addCriterion("r1 is not null");
            return (Criteria) this;
        }

        public Criteria andR1EqualTo(String value) {
            addCriterion("r1 =", value, "r1");
            return (Criteria) this;
        }

        public Criteria andR1NotEqualTo(String value) {
            addCriterion("r1 <>", value, "r1");
            return (Criteria) this;
        }

        public Criteria andR1GreaterThan(String value) {
            addCriterion("r1 >", value, "r1");
            return (Criteria) this;
        }

        public Criteria andR1GreaterThanOrEqualTo(String value) {
            addCriterion("r1 >=", value, "r1");
            return (Criteria) this;
        }

        public Criteria andR1LessThan(String value) {
            addCriterion("r1 <", value, "r1");
            return (Criteria) this;
        }

        public Criteria andR1LessThanOrEqualTo(String value) {
            addCriterion("r1 <=", value, "r1");
            return (Criteria) this;
        }

        public Criteria andR1Like(String value) {
            addCriterion("r1 like", value, "r1");
            return (Criteria) this;
        }

        public Criteria andR1NotLike(String value) {
            addCriterion("r1 not like", value, "r1");
            return (Criteria) this;
        }

        public Criteria andR1In(List<String> values) {
            addCriterion("r1 in", values, "r1");
            return (Criteria) this;
        }

        public Criteria andR1NotIn(List<String> values) {
            addCriterion("r1 not in", values, "r1");
            return (Criteria) this;
        }

        public Criteria andR1Between(String value1, String value2) {
            addCriterion("r1 between", value1, value2, "r1");
            return (Criteria) this;
        }

        public Criteria andR1NotBetween(String value1, String value2) {
            addCriterion("r1 not between", value1, value2, "r1");
            return (Criteria) this;
        }

        public Criteria andR2IsNull() {
            addCriterion("r2 is null");
            return (Criteria) this;
        }

        public Criteria andR2IsNotNull() {
            addCriterion("r2 is not null");
            return (Criteria) this;
        }

        public Criteria andR2EqualTo(String value) {
            addCriterion("r2 =", value, "r2");
            return (Criteria) this;
        }

        public Criteria andR2NotEqualTo(String value) {
            addCriterion("r2 <>", value, "r2");
            return (Criteria) this;
        }

        public Criteria andR2GreaterThan(String value) {
            addCriterion("r2 >", value, "r2");
            return (Criteria) this;
        }

        public Criteria andR2GreaterThanOrEqualTo(String value) {
            addCriterion("r2 >=", value, "r2");
            return (Criteria) this;
        }

        public Criteria andR2LessThan(String value) {
            addCriterion("r2 <", value, "r2");
            return (Criteria) this;
        }

        public Criteria andR2LessThanOrEqualTo(String value) {
            addCriterion("r2 <=", value, "r2");
            return (Criteria) this;
        }

        public Criteria andR2Like(String value) {
            addCriterion("r2 like", value, "r2");
            return (Criteria) this;
        }

        public Criteria andR2NotLike(String value) {
            addCriterion("r2 not like", value, "r2");
            return (Criteria) this;
        }

        public Criteria andR2In(List<String> values) {
            addCriterion("r2 in", values, "r2");
            return (Criteria) this;
        }

        public Criteria andR2NotIn(List<String> values) {
            addCriterion("r2 not in", values, "r2");
            return (Criteria) this;
        }

        public Criteria andR2Between(String value1, String value2) {
            addCriterion("r2 between", value1, value2, "r2");
            return (Criteria) this;
        }

        public Criteria andR2NotBetween(String value1, String value2) {
            addCriterion("r2 not between", value1, value2, "r2");
            return (Criteria) this;
        }

        public Criteria andR3IsNull() {
            addCriterion("r3 is null");
            return (Criteria) this;
        }

        public Criteria andR3IsNotNull() {
            addCriterion("r3 is not null");
            return (Criteria) this;
        }

        public Criteria andR3EqualTo(String value) {
            addCriterion("r3 =", value, "r3");
            return (Criteria) this;
        }

        public Criteria andR3NotEqualTo(String value) {
            addCriterion("r3 <>", value, "r3");
            return (Criteria) this;
        }

        public Criteria andR3GreaterThan(String value) {
            addCriterion("r3 >", value, "r3");
            return (Criteria) this;
        }

        public Criteria andR3GreaterThanOrEqualTo(String value) {
            addCriterion("r3 >=", value, "r3");
            return (Criteria) this;
        }

        public Criteria andR3LessThan(String value) {
            addCriterion("r3 <", value, "r3");
            return (Criteria) this;
        }

        public Criteria andR3LessThanOrEqualTo(String value) {
            addCriterion("r3 <=", value, "r3");
            return (Criteria) this;
        }

        public Criteria andR3Like(String value) {
            addCriterion("r3 like", value, "r3");
            return (Criteria) this;
        }

        public Criteria andR3NotLike(String value) {
            addCriterion("r3 not like", value, "r3");
            return (Criteria) this;
        }

        public Criteria andR3In(List<String> values) {
            addCriterion("r3 in", values, "r3");
            return (Criteria) this;
        }

        public Criteria andR3NotIn(List<String> values) {
            addCriterion("r3 not in", values, "r3");
            return (Criteria) this;
        }

        public Criteria andR3Between(String value1, String value2) {
            addCriterion("r3 between", value1, value2, "r3");
            return (Criteria) this;
        }

        public Criteria andR3NotBetween(String value1, String value2) {
            addCriterion("r3 not between", value1, value2, "r3");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table laud
     *
     * @mbggenerated do_not_delete_during_merge Mon Jan 02 17:35:41 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table laud
     *
     * @mbggenerated Mon Jan 02 17:35:41 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}