package com.edu.ccut.pojo;

import java.util.Date;

public class Member extends MemberKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.username
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.truename
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	private String truename;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.cipher
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	private String cipher;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.level
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	private Integer level;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.phone
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	private String phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.headimg
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	private String headimg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.state
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	private Integer state;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.motto
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	private String motto;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.sex
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	private Integer sex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.age
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	private Integer age;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.focusmenum
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	private Integer focusmenum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.focusothernum
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	private Integer focusothernum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.website
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	private String website;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.lastip
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	private String lastip;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.createdate
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	private Date createdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.communityid
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	private Integer communityid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.handletime
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	private Date handletime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.validatecode
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	private String validatecode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.r1
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	private String r1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.r2
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	private String r2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.r3
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	private String r3;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.r4
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	private String r4;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.r5
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	private String r5;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.username
	 * @return  the value of member.username
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.username
	 * @param username  the value for member.username
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	public void setUsername(String username) {
		this.username = username == null ? null : username.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.truename
	 * @return  the value of member.truename
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	public String getTruename() {
		return truename;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.truename
	 * @param truename  the value for member.truename
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	public void setTruename(String truename) {
		this.truename = truename == null ? null : truename.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.cipher
	 * @return  the value of member.cipher
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	public String getCipher() {
		return cipher;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.cipher
	 * @param cipher  the value for member.cipher
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	public void setCipher(String cipher) {
		this.cipher = cipher == null ? null : cipher.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.level
	 * @return  the value of member.level
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	public Integer getLevel() {
		return level;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.level
	 * @param level  the value for member.level
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	public void setLevel(Integer level) {
		this.level = level;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.phone
	 * @return  the value of member.phone
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.phone
	 * @param phone  the value for member.phone
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	public void setPhone(String phone) {
		this.phone = phone == null ? null : phone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.headimg
	 * @return  the value of member.headimg
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	public String getHeadimg() {
		return headimg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.headimg
	 * @param headimg  the value for member.headimg
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	public void setHeadimg(String headimg) {
		this.headimg = headimg == null ? null : headimg.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.state
	 * @return  the value of member.state
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	public Integer getState() {
		return state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.state
	 * @param state  the value for member.state
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	public void setState(Integer state) {
		this.state = state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.motto
	 * @return  the value of member.motto
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	public String getMotto() {
		return motto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.motto
	 * @param motto  the value for member.motto
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	public void setMotto(String motto) {
		this.motto = motto == null ? null : motto.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.sex
	 * @return  the value of member.sex
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	public Integer getSex() {
		return sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.sex
	 * @param sex  the value for member.sex
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	public void setSex(Integer sex) {
		this.sex = sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.age
	 * @return  the value of member.age
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	public Integer getAge() {
		return age;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.age
	 * @param age  the value for member.age
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	public void setAge(Integer age) {
		this.age = age;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.focusmenum
	 * @return  the value of member.focusmenum
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	public Integer getFocusmenum() {
		return focusmenum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.focusmenum
	 * @param focusmenum  the value for member.focusmenum
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	public void setFocusmenum(Integer focusmenum) {
		this.focusmenum = focusmenum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.focusothernum
	 * @return  the value of member.focusothernum
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	public Integer getFocusothernum() {
		return focusothernum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.focusothernum
	 * @param focusothernum  the value for member.focusothernum
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	public void setFocusothernum(Integer focusothernum) {
		this.focusothernum = focusothernum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.website
	 * @return  the value of member.website
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	public String getWebsite() {
		return website;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.website
	 * @param website  the value for member.website
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	public void setWebsite(String website) {
		this.website = website == null ? null : website.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.lastip
	 * @return  the value of member.lastip
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	public String getLastip() {
		return lastip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.lastip
	 * @param lastip  the value for member.lastip
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	public void setLastip(String lastip) {
		this.lastip = lastip == null ? null : lastip.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.createdate
	 * @return  the value of member.createdate
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	public Date getCreatedate() {
		return createdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.createdate
	 * @param createdate  the value for member.createdate
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.communityid
	 * @return  the value of member.communityid
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	public Integer getCommunityid() {
		return communityid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.communityid
	 * @param communityid  the value for member.communityid
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	public void setCommunityid(Integer communityid) {
		this.communityid = communityid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.handletime
	 * @return  the value of member.handletime
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	public Date getHandletime() {
		return handletime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.handletime
	 * @param handletime  the value for member.handletime
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	public void setHandletime(Date handletime) {
		this.handletime = handletime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.validatecode
	 * @return  the value of member.validatecode
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	public String getValidatecode() {
		return validatecode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.validatecode
	 * @param validatecode  the value for member.validatecode
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	public void setValidatecode(String validatecode) {
		this.validatecode = validatecode == null ? null : validatecode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.r1
	 * @return  the value of member.r1
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	public String getR1() {
		return r1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.r1
	 * @param r1  the value for member.r1
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	public void setR1(String r1) {
		this.r1 = r1 == null ? null : r1.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.r2
	 * @return  the value of member.r2
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	public String getR2() {
		return r2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.r2
	 * @param r2  the value for member.r2
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	public void setR2(String r2) {
		this.r2 = r2 == null ? null : r2.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.r3
	 * @return  the value of member.r3
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	public String getR3() {
		return r3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.r3
	 * @param r3  the value for member.r3
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	public void setR3(String r3) {
		this.r3 = r3 == null ? null : r3.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.r4
	 * @return  the value of member.r4
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	public String getR4() {
		return r4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.r4
	 * @param r4  the value for member.r4
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	public void setR4(String r4) {
		this.r4 = r4 == null ? null : r4.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.r5
	 * @return  the value of member.r5
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	public String getR5() {
		return r5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.r5
	 * @param r5  the value for member.r5
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	public void setR5(String r5) {
		this.r5 = r5 == null ? null : r5.trim();
	}
}