package com.edu.ccut.pojo;

import java.util.Date;

public class Messageimg {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column messageimg.id
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column messageimg.compressimgurl
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	private String compressimgurl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column messageimg.sourceimgname
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	private String sourceimgname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column messageimg.sourcimgurl
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	private String sourcimgurl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column messageimg.saveurl
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	private String saveurl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column messageimg.sourcimgwidth
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	private Integer sourcimgwidth;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column messageimg.sourceimgheight
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	private Integer sourceimgheight;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column messageimg.circle
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	private String circle;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column messageimg.imgaddress
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	private String imgaddress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column messageimg.addresscode
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	private Integer addresscode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column messageimg.content
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	private String content;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column messageimg.createdate
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	private Date createdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column messageimg.state
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	private Integer state;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column messageimg.commentnum
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	private Integer commentnum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column messageimg.laudnum
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	private Integer laudnum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column messageimg.r1
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	private String r1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column messageimg.r2
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	private String r2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column messageimg.r3
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	private String r3;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column messageimg.r4
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	private String r4;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column messageimg.r5
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	private String r5;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column messageimg.id
	 * @return  the value of messageimg.id
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column messageimg.id
	 * @param id  the value for messageimg.id
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column messageimg.compressimgurl
	 * @return  the value of messageimg.compressimgurl
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	public String getCompressimgurl() {
		return compressimgurl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column messageimg.compressimgurl
	 * @param compressimgurl  the value for messageimg.compressimgurl
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	public void setCompressimgurl(String compressimgurl) {
		this.compressimgurl = compressimgurl == null ? null : compressimgurl.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column messageimg.sourceimgname
	 * @return  the value of messageimg.sourceimgname
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	public String getSourceimgname() {
		return sourceimgname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column messageimg.sourceimgname
	 * @param sourceimgname  the value for messageimg.sourceimgname
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	public void setSourceimgname(String sourceimgname) {
		this.sourceimgname = sourceimgname == null ? null : sourceimgname.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column messageimg.sourcimgurl
	 * @return  the value of messageimg.sourcimgurl
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	public String getSourcimgurl() {
		return sourcimgurl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column messageimg.sourcimgurl
	 * @param sourcimgurl  the value for messageimg.sourcimgurl
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	public void setSourcimgurl(String sourcimgurl) {
		this.sourcimgurl = sourcimgurl == null ? null : sourcimgurl.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column messageimg.saveurl
	 * @return  the value of messageimg.saveurl
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	public String getSaveurl() {
		return saveurl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column messageimg.saveurl
	 * @param saveurl  the value for messageimg.saveurl
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	public void setSaveurl(String saveurl) {
		this.saveurl = saveurl == null ? null : saveurl.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column messageimg.sourcimgwidth
	 * @return  the value of messageimg.sourcimgwidth
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	public Integer getSourcimgwidth() {
		return sourcimgwidth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column messageimg.sourcimgwidth
	 * @param sourcimgwidth  the value for messageimg.sourcimgwidth
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	public void setSourcimgwidth(Integer sourcimgwidth) {
		this.sourcimgwidth = sourcimgwidth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column messageimg.sourceimgheight
	 * @return  the value of messageimg.sourceimgheight
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	public Integer getSourceimgheight() {
		return sourceimgheight;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column messageimg.sourceimgheight
	 * @param sourceimgheight  the value for messageimg.sourceimgheight
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	public void setSourceimgheight(Integer sourceimgheight) {
		this.sourceimgheight = sourceimgheight;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column messageimg.circle
	 * @return  the value of messageimg.circle
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	public String getCircle() {
		return circle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column messageimg.circle
	 * @param circle  the value for messageimg.circle
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	public void setCircle(String circle) {
		this.circle = circle == null ? null : circle.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column messageimg.imgaddress
	 * @return  the value of messageimg.imgaddress
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	public String getImgaddress() {
		return imgaddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column messageimg.imgaddress
	 * @param imgaddress  the value for messageimg.imgaddress
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	public void setImgaddress(String imgaddress) {
		this.imgaddress = imgaddress == null ? null : imgaddress.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column messageimg.addresscode
	 * @return  the value of messageimg.addresscode
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	public Integer getAddresscode() {
		return addresscode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column messageimg.addresscode
	 * @param addresscode  the value for messageimg.addresscode
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	public void setAddresscode(Integer addresscode) {
		this.addresscode = addresscode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column messageimg.content
	 * @return  the value of messageimg.content
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column messageimg.content
	 * @param content  the value for messageimg.content
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	public void setContent(String content) {
		this.content = content == null ? null : content.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column messageimg.createdate
	 * @return  the value of messageimg.createdate
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	public Date getCreatedate() {
		return createdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column messageimg.createdate
	 * @param createdate  the value for messageimg.createdate
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column messageimg.state
	 * @return  the value of messageimg.state
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	public Integer getState() {
		return state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column messageimg.state
	 * @param state  the value for messageimg.state
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	public void setState(Integer state) {
		this.state = state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column messageimg.commentnum
	 * @return  the value of messageimg.commentnum
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	public Integer getCommentnum() {
		return commentnum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column messageimg.commentnum
	 * @param commentnum  the value for messageimg.commentnum
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	public void setCommentnum(Integer commentnum) {
		this.commentnum = commentnum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column messageimg.laudnum
	 * @return  the value of messageimg.laudnum
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	public Integer getLaudnum() {
		return laudnum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column messageimg.laudnum
	 * @param laudnum  the value for messageimg.laudnum
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	public void setLaudnum(Integer laudnum) {
		this.laudnum = laudnum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column messageimg.r1
	 * @return  the value of messageimg.r1
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	public String getR1() {
		return r1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column messageimg.r1
	 * @param r1  the value for messageimg.r1
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	public void setR1(String r1) {
		this.r1 = r1 == null ? null : r1.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column messageimg.r2
	 * @return  the value of messageimg.r2
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	public String getR2() {
		return r2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column messageimg.r2
	 * @param r2  the value for messageimg.r2
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	public void setR2(String r2) {
		this.r2 = r2 == null ? null : r2.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column messageimg.r3
	 * @return  the value of messageimg.r3
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	public String getR3() {
		return r3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column messageimg.r3
	 * @param r3  the value for messageimg.r3
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	public void setR3(String r3) {
		this.r3 = r3 == null ? null : r3.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column messageimg.r4
	 * @return  the value of messageimg.r4
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	public String getR4() {
		return r4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column messageimg.r4
	 * @param r4  the value for messageimg.r4
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	public void setR4(String r4) {
		this.r4 = r4 == null ? null : r4.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column messageimg.r5
	 * @return  the value of messageimg.r5
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	public String getR5() {
		return r5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column messageimg.r5
	 * @param r5  the value for messageimg.r5
	 * @mbggenerated  Sat Aug 13 15:20:16 CST 2016
	 */
	public void setR5(String r5) {
		this.r5 = r5 == null ? null : r5.trim();
	}
}