package com.edu.ccut.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class MessageimgExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table messageimg
     *
     * @mbggenerated Mon Jan 02 17:35:41 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table messageimg
     *
     * @mbggenerated Mon Jan 02 17:35:41 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table messageimg
     *
     * @mbggenerated Mon Jan 02 17:35:41 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messageimg
     *
     * @mbggenerated Mon Jan 02 17:35:41 CST 2017
     */
    public MessageimgExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messageimg
     *
     * @mbggenerated Mon Jan 02 17:35:41 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messageimg
     *
     * @mbggenerated Mon Jan 02 17:35:41 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messageimg
     *
     * @mbggenerated Mon Jan 02 17:35:41 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messageimg
     *
     * @mbggenerated Mon Jan 02 17:35:41 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messageimg
     *
     * @mbggenerated Mon Jan 02 17:35:41 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messageimg
     *
     * @mbggenerated Mon Jan 02 17:35:41 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messageimg
     *
     * @mbggenerated Mon Jan 02 17:35:41 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messageimg
     *
     * @mbggenerated Mon Jan 02 17:35:41 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messageimg
     *
     * @mbggenerated Mon Jan 02 17:35:41 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messageimg
     *
     * @mbggenerated Mon Jan 02 17:35:41 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table messageimg
     *
     * @mbggenerated Mon Jan 02 17:35:41 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andMemberidIsNull() {
            addCriterion("memberid is null");
            return (Criteria) this;
        }

        public Criteria andMemberidIsNotNull() {
            addCriterion("memberid is not null");
            return (Criteria) this;
        }

        public Criteria andMemberidEqualTo(Integer value) {
            addCriterion("memberid =", value, "memberid");
            return (Criteria) this;
        }

        public Criteria andMemberidNotEqualTo(Integer value) {
            addCriterion("memberid <>", value, "memberid");
            return (Criteria) this;
        }

        public Criteria andMemberidGreaterThan(Integer value) {
            addCriterion("memberid >", value, "memberid");
            return (Criteria) this;
        }

        public Criteria andMemberidGreaterThanOrEqualTo(Integer value) {
            addCriterion("memberid >=", value, "memberid");
            return (Criteria) this;
        }

        public Criteria andMemberidLessThan(Integer value) {
            addCriterion("memberid <", value, "memberid");
            return (Criteria) this;
        }

        public Criteria andMemberidLessThanOrEqualTo(Integer value) {
            addCriterion("memberid <=", value, "memberid");
            return (Criteria) this;
        }

        public Criteria andMemberidIn(List<Integer> values) {
            addCriterion("memberid in", values, "memberid");
            return (Criteria) this;
        }

        public Criteria andMemberidNotIn(List<Integer> values) {
            addCriterion("memberid not in", values, "memberid");
            return (Criteria) this;
        }

        public Criteria andMemberidBetween(Integer value1, Integer value2) {
            addCriterion("memberid between", value1, value2, "memberid");
            return (Criteria) this;
        }

        public Criteria andMemberidNotBetween(Integer value1, Integer value2) {
            addCriterion("memberid not between", value1, value2, "memberid");
            return (Criteria) this;
        }

        public Criteria andCompressimgurlIsNull() {
            addCriterion("compressimgurl is null");
            return (Criteria) this;
        }

        public Criteria andCompressimgurlIsNotNull() {
            addCriterion("compressimgurl is not null");
            return (Criteria) this;
        }

        public Criteria andCompressimgurlEqualTo(String value) {
            addCriterion("compressimgurl =", value, "compressimgurl");
            return (Criteria) this;
        }

        public Criteria andCompressimgurlNotEqualTo(String value) {
            addCriterion("compressimgurl <>", value, "compressimgurl");
            return (Criteria) this;
        }

        public Criteria andCompressimgurlGreaterThan(String value) {
            addCriterion("compressimgurl >", value, "compressimgurl");
            return (Criteria) this;
        }

        public Criteria andCompressimgurlGreaterThanOrEqualTo(String value) {
            addCriterion("compressimgurl >=", value, "compressimgurl");
            return (Criteria) this;
        }

        public Criteria andCompressimgurlLessThan(String value) {
            addCriterion("compressimgurl <", value, "compressimgurl");
            return (Criteria) this;
        }

        public Criteria andCompressimgurlLessThanOrEqualTo(String value) {
            addCriterion("compressimgurl <=", value, "compressimgurl");
            return (Criteria) this;
        }

        public Criteria andCompressimgurlLike(String value) {
            addCriterion("compressimgurl like", value, "compressimgurl");
            return (Criteria) this;
        }

        public Criteria andCompressimgurlNotLike(String value) {
            addCriterion("compressimgurl not like", value, "compressimgurl");
            return (Criteria) this;
        }

        public Criteria andCompressimgurlIn(List<String> values) {
            addCriterion("compressimgurl in", values, "compressimgurl");
            return (Criteria) this;
        }

        public Criteria andCompressimgurlNotIn(List<String> values) {
            addCriterion("compressimgurl not in", values, "compressimgurl");
            return (Criteria) this;
        }

        public Criteria andCompressimgurlBetween(String value1, String value2) {
            addCriterion("compressimgurl between", value1, value2, "compressimgurl");
            return (Criteria) this;
        }

        public Criteria andCompressimgurlNotBetween(String value1, String value2) {
            addCriterion("compressimgurl not between", value1, value2, "compressimgurl");
            return (Criteria) this;
        }

        public Criteria andSourceimgnameIsNull() {
            addCriterion("sourceimgname is null");
            return (Criteria) this;
        }

        public Criteria andSourceimgnameIsNotNull() {
            addCriterion("sourceimgname is not null");
            return (Criteria) this;
        }

        public Criteria andSourceimgnameEqualTo(String value) {
            addCriterion("sourceimgname =", value, "sourceimgname");
            return (Criteria) this;
        }

        public Criteria andSourceimgnameNotEqualTo(String value) {
            addCriterion("sourceimgname <>", value, "sourceimgname");
            return (Criteria) this;
        }

        public Criteria andSourceimgnameGreaterThan(String value) {
            addCriterion("sourceimgname >", value, "sourceimgname");
            return (Criteria) this;
        }

        public Criteria andSourceimgnameGreaterThanOrEqualTo(String value) {
            addCriterion("sourceimgname >=", value, "sourceimgname");
            return (Criteria) this;
        }

        public Criteria andSourceimgnameLessThan(String value) {
            addCriterion("sourceimgname <", value, "sourceimgname");
            return (Criteria) this;
        }

        public Criteria andSourceimgnameLessThanOrEqualTo(String value) {
            addCriterion("sourceimgname <=", value, "sourceimgname");
            return (Criteria) this;
        }

        public Criteria andSourceimgnameLike(String value) {
            addCriterion("sourceimgname like", value, "sourceimgname");
            return (Criteria) this;
        }

        public Criteria andSourceimgnameNotLike(String value) {
            addCriterion("sourceimgname not like", value, "sourceimgname");
            return (Criteria) this;
        }

        public Criteria andSourceimgnameIn(List<String> values) {
            addCriterion("sourceimgname in", values, "sourceimgname");
            return (Criteria) this;
        }

        public Criteria andSourceimgnameNotIn(List<String> values) {
            addCriterion("sourceimgname not in", values, "sourceimgname");
            return (Criteria) this;
        }

        public Criteria andSourceimgnameBetween(String value1, String value2) {
            addCriterion("sourceimgname between", value1, value2, "sourceimgname");
            return (Criteria) this;
        }

        public Criteria andSourceimgnameNotBetween(String value1, String value2) {
            addCriterion("sourceimgname not between", value1, value2, "sourceimgname");
            return (Criteria) this;
        }

        public Criteria andSourcimgurlIsNull() {
            addCriterion("sourcimgurl is null");
            return (Criteria) this;
        }

        public Criteria andSourcimgurlIsNotNull() {
            addCriterion("sourcimgurl is not null");
            return (Criteria) this;
        }

        public Criteria andSourcimgurlEqualTo(String value) {
            addCriterion("sourcimgurl =", value, "sourcimgurl");
            return (Criteria) this;
        }

        public Criteria andSourcimgurlNotEqualTo(String value) {
            addCriterion("sourcimgurl <>", value, "sourcimgurl");
            return (Criteria) this;
        }

        public Criteria andSourcimgurlGreaterThan(String value) {
            addCriterion("sourcimgurl >", value, "sourcimgurl");
            return (Criteria) this;
        }

        public Criteria andSourcimgurlGreaterThanOrEqualTo(String value) {
            addCriterion("sourcimgurl >=", value, "sourcimgurl");
            return (Criteria) this;
        }

        public Criteria andSourcimgurlLessThan(String value) {
            addCriterion("sourcimgurl <", value, "sourcimgurl");
            return (Criteria) this;
        }

        public Criteria andSourcimgurlLessThanOrEqualTo(String value) {
            addCriterion("sourcimgurl <=", value, "sourcimgurl");
            return (Criteria) this;
        }

        public Criteria andSourcimgurlLike(String value) {
            addCriterion("sourcimgurl like", value, "sourcimgurl");
            return (Criteria) this;
        }

        public Criteria andSourcimgurlNotLike(String value) {
            addCriterion("sourcimgurl not like", value, "sourcimgurl");
            return (Criteria) this;
        }

        public Criteria andSourcimgurlIn(List<String> values) {
            addCriterion("sourcimgurl in", values, "sourcimgurl");
            return (Criteria) this;
        }

        public Criteria andSourcimgurlNotIn(List<String> values) {
            addCriterion("sourcimgurl not in", values, "sourcimgurl");
            return (Criteria) this;
        }

        public Criteria andSourcimgurlBetween(String value1, String value2) {
            addCriterion("sourcimgurl between", value1, value2, "sourcimgurl");
            return (Criteria) this;
        }

        public Criteria andSourcimgurlNotBetween(String value1, String value2) {
            addCriterion("sourcimgurl not between", value1, value2, "sourcimgurl");
            return (Criteria) this;
        }

        public Criteria andSaveurlIsNull() {
            addCriterion("saveurl is null");
            return (Criteria) this;
        }

        public Criteria andSaveurlIsNotNull() {
            addCriterion("saveurl is not null");
            return (Criteria) this;
        }

        public Criteria andSaveurlEqualTo(String value) {
            addCriterion("saveurl =", value, "saveurl");
            return (Criteria) this;
        }

        public Criteria andSaveurlNotEqualTo(String value) {
            addCriterion("saveurl <>", value, "saveurl");
            return (Criteria) this;
        }

        public Criteria andSaveurlGreaterThan(String value) {
            addCriterion("saveurl >", value, "saveurl");
            return (Criteria) this;
        }

        public Criteria andSaveurlGreaterThanOrEqualTo(String value) {
            addCriterion("saveurl >=", value, "saveurl");
            return (Criteria) this;
        }

        public Criteria andSaveurlLessThan(String value) {
            addCriterion("saveurl <", value, "saveurl");
            return (Criteria) this;
        }

        public Criteria andSaveurlLessThanOrEqualTo(String value) {
            addCriterion("saveurl <=", value, "saveurl");
            return (Criteria) this;
        }

        public Criteria andSaveurlLike(String value) {
            addCriterion("saveurl like", value, "saveurl");
            return (Criteria) this;
        }

        public Criteria andSaveurlNotLike(String value) {
            addCriterion("saveurl not like", value, "saveurl");
            return (Criteria) this;
        }

        public Criteria andSaveurlIn(List<String> values) {
            addCriterion("saveurl in", values, "saveurl");
            return (Criteria) this;
        }

        public Criteria andSaveurlNotIn(List<String> values) {
            addCriterion("saveurl not in", values, "saveurl");
            return (Criteria) this;
        }

        public Criteria andSaveurlBetween(String value1, String value2) {
            addCriterion("saveurl between", value1, value2, "saveurl");
            return (Criteria) this;
        }

        public Criteria andSaveurlNotBetween(String value1, String value2) {
            addCriterion("saveurl not between", value1, value2, "saveurl");
            return (Criteria) this;
        }

        public Criteria andSourcimgwidthIsNull() {
            addCriterion("sourcimgwidth is null");
            return (Criteria) this;
        }

        public Criteria andSourcimgwidthIsNotNull() {
            addCriterion("sourcimgwidth is not null");
            return (Criteria) this;
        }

        public Criteria andSourcimgwidthEqualTo(Integer value) {
            addCriterion("sourcimgwidth =", value, "sourcimgwidth");
            return (Criteria) this;
        }

        public Criteria andSourcimgwidthNotEqualTo(Integer value) {
            addCriterion("sourcimgwidth <>", value, "sourcimgwidth");
            return (Criteria) this;
        }

        public Criteria andSourcimgwidthGreaterThan(Integer value) {
            addCriterion("sourcimgwidth >", value, "sourcimgwidth");
            return (Criteria) this;
        }

        public Criteria andSourcimgwidthGreaterThanOrEqualTo(Integer value) {
            addCriterion("sourcimgwidth >=", value, "sourcimgwidth");
            return (Criteria) this;
        }

        public Criteria andSourcimgwidthLessThan(Integer value) {
            addCriterion("sourcimgwidth <", value, "sourcimgwidth");
            return (Criteria) this;
        }

        public Criteria andSourcimgwidthLessThanOrEqualTo(Integer value) {
            addCriterion("sourcimgwidth <=", value, "sourcimgwidth");
            return (Criteria) this;
        }

        public Criteria andSourcimgwidthIn(List<Integer> values) {
            addCriterion("sourcimgwidth in", values, "sourcimgwidth");
            return (Criteria) this;
        }

        public Criteria andSourcimgwidthNotIn(List<Integer> values) {
            addCriterion("sourcimgwidth not in", values, "sourcimgwidth");
            return (Criteria) this;
        }

        public Criteria andSourcimgwidthBetween(Integer value1, Integer value2) {
            addCriterion("sourcimgwidth between", value1, value2, "sourcimgwidth");
            return (Criteria) this;
        }

        public Criteria andSourcimgwidthNotBetween(Integer value1, Integer value2) {
            addCriterion("sourcimgwidth not between", value1, value2, "sourcimgwidth");
            return (Criteria) this;
        }

        public Criteria andSourceimgheightIsNull() {
            addCriterion("sourceimgheight is null");
            return (Criteria) this;
        }

        public Criteria andSourceimgheightIsNotNull() {
            addCriterion("sourceimgheight is not null");
            return (Criteria) this;
        }

        public Criteria andSourceimgheightEqualTo(Integer value) {
            addCriterion("sourceimgheight =", value, "sourceimgheight");
            return (Criteria) this;
        }

        public Criteria andSourceimgheightNotEqualTo(Integer value) {
            addCriterion("sourceimgheight <>", value, "sourceimgheight");
            return (Criteria) this;
        }

        public Criteria andSourceimgheightGreaterThan(Integer value) {
            addCriterion("sourceimgheight >", value, "sourceimgheight");
            return (Criteria) this;
        }

        public Criteria andSourceimgheightGreaterThanOrEqualTo(Integer value) {
            addCriterion("sourceimgheight >=", value, "sourceimgheight");
            return (Criteria) this;
        }

        public Criteria andSourceimgheightLessThan(Integer value) {
            addCriterion("sourceimgheight <", value, "sourceimgheight");
            return (Criteria) this;
        }

        public Criteria andSourceimgheightLessThanOrEqualTo(Integer value) {
            addCriterion("sourceimgheight <=", value, "sourceimgheight");
            return (Criteria) this;
        }

        public Criteria andSourceimgheightIn(List<Integer> values) {
            addCriterion("sourceimgheight in", values, "sourceimgheight");
            return (Criteria) this;
        }

        public Criteria andSourceimgheightNotIn(List<Integer> values) {
            addCriterion("sourceimgheight not in", values, "sourceimgheight");
            return (Criteria) this;
        }

        public Criteria andSourceimgheightBetween(Integer value1, Integer value2) {
            addCriterion("sourceimgheight between", value1, value2, "sourceimgheight");
            return (Criteria) this;
        }

        public Criteria andSourceimgheightNotBetween(Integer value1, Integer value2) {
            addCriterion("sourceimgheight not between", value1, value2, "sourceimgheight");
            return (Criteria) this;
        }

        public Criteria andCircleIsNull() {
            addCriterion("circle is null");
            return (Criteria) this;
        }

        public Criteria andCircleIsNotNull() {
            addCriterion("circle is not null");
            return (Criteria) this;
        }

        public Criteria andCircleEqualTo(String value) {
            addCriterion("circle =", value, "circle");
            return (Criteria) this;
        }

        public Criteria andCircleNotEqualTo(String value) {
            addCriterion("circle <>", value, "circle");
            return (Criteria) this;
        }

        public Criteria andCircleGreaterThan(String value) {
            addCriterion("circle >", value, "circle");
            return (Criteria) this;
        }

        public Criteria andCircleGreaterThanOrEqualTo(String value) {
            addCriterion("circle >=", value, "circle");
            return (Criteria) this;
        }

        public Criteria andCircleLessThan(String value) {
            addCriterion("circle <", value, "circle");
            return (Criteria) this;
        }

        public Criteria andCircleLessThanOrEqualTo(String value) {
            addCriterion("circle <=", value, "circle");
            return (Criteria) this;
        }

        public Criteria andCircleLike(String value) {
            addCriterion("circle like", value, "circle");
            return (Criteria) this;
        }

        public Criteria andCircleNotLike(String value) {
            addCriterion("circle not like", value, "circle");
            return (Criteria) this;
        }

        public Criteria andCircleIn(List<String> values) {
            addCriterion("circle in", values, "circle");
            return (Criteria) this;
        }

        public Criteria andCircleNotIn(List<String> values) {
            addCriterion("circle not in", values, "circle");
            return (Criteria) this;
        }

        public Criteria andCircleBetween(String value1, String value2) {
            addCriterion("circle between", value1, value2, "circle");
            return (Criteria) this;
        }

        public Criteria andCircleNotBetween(String value1, String value2) {
            addCriterion("circle not between", value1, value2, "circle");
            return (Criteria) this;
        }

        public Criteria andImgaddressIsNull() {
            addCriterion("imgaddress is null");
            return (Criteria) this;
        }

        public Criteria andImgaddressIsNotNull() {
            addCriterion("imgaddress is not null");
            return (Criteria) this;
        }

        public Criteria andImgaddressEqualTo(String value) {
            addCriterion("imgaddress =", value, "imgaddress");
            return (Criteria) this;
        }

        public Criteria andImgaddressNotEqualTo(String value) {
            addCriterion("imgaddress <>", value, "imgaddress");
            return (Criteria) this;
        }

        public Criteria andImgaddressGreaterThan(String value) {
            addCriterion("imgaddress >", value, "imgaddress");
            return (Criteria) this;
        }

        public Criteria andImgaddressGreaterThanOrEqualTo(String value) {
            addCriterion("imgaddress >=", value, "imgaddress");
            return (Criteria) this;
        }

        public Criteria andImgaddressLessThan(String value) {
            addCriterion("imgaddress <", value, "imgaddress");
            return (Criteria) this;
        }

        public Criteria andImgaddressLessThanOrEqualTo(String value) {
            addCriterion("imgaddress <=", value, "imgaddress");
            return (Criteria) this;
        }

        public Criteria andImgaddressLike(String value) {
            addCriterion("imgaddress like", value, "imgaddress");
            return (Criteria) this;
        }

        public Criteria andImgaddressNotLike(String value) {
            addCriterion("imgaddress not like", value, "imgaddress");
            return (Criteria) this;
        }

        public Criteria andImgaddressIn(List<String> values) {
            addCriterion("imgaddress in", values, "imgaddress");
            return (Criteria) this;
        }

        public Criteria andImgaddressNotIn(List<String> values) {
            addCriterion("imgaddress not in", values, "imgaddress");
            return (Criteria) this;
        }

        public Criteria andImgaddressBetween(String value1, String value2) {
            addCriterion("imgaddress between", value1, value2, "imgaddress");
            return (Criteria) this;
        }

        public Criteria andImgaddressNotBetween(String value1, String value2) {
            addCriterion("imgaddress not between", value1, value2, "imgaddress");
            return (Criteria) this;
        }

        public Criteria andAddresscodeIsNull() {
            addCriterion("addresscode is null");
            return (Criteria) this;
        }

        public Criteria andAddresscodeIsNotNull() {
            addCriterion("addresscode is not null");
            return (Criteria) this;
        }

        public Criteria andAddresscodeEqualTo(Integer value) {
            addCriterion("addresscode =", value, "addresscode");
            return (Criteria) this;
        }

        public Criteria andAddresscodeNotEqualTo(Integer value) {
            addCriterion("addresscode <>", value, "addresscode");
            return (Criteria) this;
        }

        public Criteria andAddresscodeGreaterThan(Integer value) {
            addCriterion("addresscode >", value, "addresscode");
            return (Criteria) this;
        }

        public Criteria andAddresscodeGreaterThanOrEqualTo(Integer value) {
            addCriterion("addresscode >=", value, "addresscode");
            return (Criteria) this;
        }

        public Criteria andAddresscodeLessThan(Integer value) {
            addCriterion("addresscode <", value, "addresscode");
            return (Criteria) this;
        }

        public Criteria andAddresscodeLessThanOrEqualTo(Integer value) {
            addCriterion("addresscode <=", value, "addresscode");
            return (Criteria) this;
        }

        public Criteria andAddresscodeIn(List<Integer> values) {
            addCriterion("addresscode in", values, "addresscode");
            return (Criteria) this;
        }

        public Criteria andAddresscodeNotIn(List<Integer> values) {
            addCriterion("addresscode not in", values, "addresscode");
            return (Criteria) this;
        }

        public Criteria andAddresscodeBetween(Integer value1, Integer value2) {
            addCriterion("addresscode between", value1, value2, "addresscode");
            return (Criteria) this;
        }

        public Criteria andAddresscodeNotBetween(Integer value1, Integer value2) {
            addCriterion("addresscode not between", value1, value2, "addresscode");
            return (Criteria) this;
        }

        public Criteria andContentIsNull() {
            addCriterion("content is null");
            return (Criteria) this;
        }

        public Criteria andContentIsNotNull() {
            addCriterion("content is not null");
            return (Criteria) this;
        }

        public Criteria andContentEqualTo(String value) {
            addCriterion("content =", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotEqualTo(String value) {
            addCriterion("content <>", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentGreaterThan(String value) {
            addCriterion("content >", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentGreaterThanOrEqualTo(String value) {
            addCriterion("content >=", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLessThan(String value) {
            addCriterion("content <", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLessThanOrEqualTo(String value) {
            addCriterion("content <=", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLike(String value) {
            addCriterion("content like", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotLike(String value) {
            addCriterion("content not like", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentIn(List<String> values) {
            addCriterion("content in", values, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotIn(List<String> values) {
            addCriterion("content not in", values, "content");
            return (Criteria) this;
        }

        public Criteria andContentBetween(String value1, String value2) {
            addCriterion("content between", value1, value2, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotBetween(String value1, String value2) {
            addCriterion("content not between", value1, value2, "content");
            return (Criteria) this;
        }

        public Criteria andCreatedateIsNull() {
            addCriterion("createdate is null");
            return (Criteria) this;
        }

        public Criteria andCreatedateIsNotNull() {
            addCriterion("createdate is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedateEqualTo(Date value) {
            addCriterion("createdate =", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotEqualTo(Date value) {
            addCriterion("createdate <>", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateGreaterThan(Date value) {
            addCriterion("createdate >", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateGreaterThanOrEqualTo(Date value) {
            addCriterion("createdate >=", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateLessThan(Date value) {
            addCriterion("createdate <", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateLessThanOrEqualTo(Date value) {
            addCriterion("createdate <=", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateIn(List<Date> values) {
            addCriterion("createdate in", values, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotIn(List<Date> values) {
            addCriterion("createdate not in", values, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateBetween(Date value1, Date value2) {
            addCriterion("createdate between", value1, value2, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotBetween(Date value1, Date value2) {
            addCriterion("createdate not between", value1, value2, "createdate");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("state is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("state is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(Integer value) {
            addCriterion("state =", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(Integer value) {
            addCriterion("state <>", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(Integer value) {
            addCriterion("state >", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(Integer value) {
            addCriterion("state >=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThan(Integer value) {
            addCriterion("state <", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(Integer value) {
            addCriterion("state <=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateIn(List<Integer> values) {
            addCriterion("state in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<Integer> values) {
            addCriterion("state not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(Integer value1, Integer value2) {
            addCriterion("state between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(Integer value1, Integer value2) {
            addCriterion("state not between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andCommentnumIsNull() {
            addCriterion("commentnum is null");
            return (Criteria) this;
        }

        public Criteria andCommentnumIsNotNull() {
            addCriterion("commentnum is not null");
            return (Criteria) this;
        }

        public Criteria andCommentnumEqualTo(Integer value) {
            addCriterion("commentnum =", value, "commentnum");
            return (Criteria) this;
        }

        public Criteria andCommentnumNotEqualTo(Integer value) {
            addCriterion("commentnum <>", value, "commentnum");
            return (Criteria) this;
        }

        public Criteria andCommentnumGreaterThan(Integer value) {
            addCriterion("commentnum >", value, "commentnum");
            return (Criteria) this;
        }

        public Criteria andCommentnumGreaterThanOrEqualTo(Integer value) {
            addCriterion("commentnum >=", value, "commentnum");
            return (Criteria) this;
        }

        public Criteria andCommentnumLessThan(Integer value) {
            addCriterion("commentnum <", value, "commentnum");
            return (Criteria) this;
        }

        public Criteria andCommentnumLessThanOrEqualTo(Integer value) {
            addCriterion("commentnum <=", value, "commentnum");
            return (Criteria) this;
        }

        public Criteria andCommentnumIn(List<Integer> values) {
            addCriterion("commentnum in", values, "commentnum");
            return (Criteria) this;
        }

        public Criteria andCommentnumNotIn(List<Integer> values) {
            addCriterion("commentnum not in", values, "commentnum");
            return (Criteria) this;
        }

        public Criteria andCommentnumBetween(Integer value1, Integer value2) {
            addCriterion("commentnum between", value1, value2, "commentnum");
            return (Criteria) this;
        }

        public Criteria andCommentnumNotBetween(Integer value1, Integer value2) {
            addCriterion("commentnum not between", value1, value2, "commentnum");
            return (Criteria) this;
        }

        public Criteria andLaudnumIsNull() {
            addCriterion("laudnum is null");
            return (Criteria) this;
        }

        public Criteria andLaudnumIsNotNull() {
            addCriterion("laudnum is not null");
            return (Criteria) this;
        }

        public Criteria andLaudnumEqualTo(Integer value) {
            addCriterion("laudnum =", value, "laudnum");
            return (Criteria) this;
        }

        public Criteria andLaudnumNotEqualTo(Integer value) {
            addCriterion("laudnum <>", value, "laudnum");
            return (Criteria) this;
        }

        public Criteria andLaudnumGreaterThan(Integer value) {
            addCriterion("laudnum >", value, "laudnum");
            return (Criteria) this;
        }

        public Criteria andLaudnumGreaterThanOrEqualTo(Integer value) {
            addCriterion("laudnum >=", value, "laudnum");
            return (Criteria) this;
        }

        public Criteria andLaudnumLessThan(Integer value) {
            addCriterion("laudnum <", value, "laudnum");
            return (Criteria) this;
        }

        public Criteria andLaudnumLessThanOrEqualTo(Integer value) {
            addCriterion("laudnum <=", value, "laudnum");
            return (Criteria) this;
        }

        public Criteria andLaudnumIn(List<Integer> values) {
            addCriterion("laudnum in", values, "laudnum");
            return (Criteria) this;
        }

        public Criteria andLaudnumNotIn(List<Integer> values) {
            addCriterion("laudnum not in", values, "laudnum");
            return (Criteria) this;
        }

        public Criteria andLaudnumBetween(Integer value1, Integer value2) {
            addCriterion("laudnum between", value1, value2, "laudnum");
            return (Criteria) this;
        }

        public Criteria andLaudnumNotBetween(Integer value1, Integer value2) {
            addCriterion("laudnum not between", value1, value2, "laudnum");
            return (Criteria) this;
        }

        public Criteria andR1IsNull() {
            addCriterion("r1 is null");
            return (Criteria) this;
        }

        public Criteria andR1IsNotNull() {
            addCriterion("r1 is not null");
            return (Criteria) this;
        }

        public Criteria andR1EqualTo(String value) {
            addCriterion("r1 =", value, "r1");
            return (Criteria) this;
        }

        public Criteria andR1NotEqualTo(String value) {
            addCriterion("r1 <>", value, "r1");
            return (Criteria) this;
        }

        public Criteria andR1GreaterThan(String value) {
            addCriterion("r1 >", value, "r1");
            return (Criteria) this;
        }

        public Criteria andR1GreaterThanOrEqualTo(String value) {
            addCriterion("r1 >=", value, "r1");
            return (Criteria) this;
        }

        public Criteria andR1LessThan(String value) {
            addCriterion("r1 <", value, "r1");
            return (Criteria) this;
        }

        public Criteria andR1LessThanOrEqualTo(String value) {
            addCriterion("r1 <=", value, "r1");
            return (Criteria) this;
        }

        public Criteria andR1Like(String value) {
            addCriterion("r1 like", value, "r1");
            return (Criteria) this;
        }

        public Criteria andR1NotLike(String value) {
            addCriterion("r1 not like", value, "r1");
            return (Criteria) this;
        }

        public Criteria andR1In(List<String> values) {
            addCriterion("r1 in", values, "r1");
            return (Criteria) this;
        }

        public Criteria andR1NotIn(List<String> values) {
            addCriterion("r1 not in", values, "r1");
            return (Criteria) this;
        }

        public Criteria andR1Between(String value1, String value2) {
            addCriterion("r1 between", value1, value2, "r1");
            return (Criteria) this;
        }

        public Criteria andR1NotBetween(String value1, String value2) {
            addCriterion("r1 not between", value1, value2, "r1");
            return (Criteria) this;
        }

        public Criteria andR2IsNull() {
            addCriterion("r2 is null");
            return (Criteria) this;
        }

        public Criteria andR2IsNotNull() {
            addCriterion("r2 is not null");
            return (Criteria) this;
        }

        public Criteria andR2EqualTo(String value) {
            addCriterion("r2 =", value, "r2");
            return (Criteria) this;
        }

        public Criteria andR2NotEqualTo(String value) {
            addCriterion("r2 <>", value, "r2");
            return (Criteria) this;
        }

        public Criteria andR2GreaterThan(String value) {
            addCriterion("r2 >", value, "r2");
            return (Criteria) this;
        }

        public Criteria andR2GreaterThanOrEqualTo(String value) {
            addCriterion("r2 >=", value, "r2");
            return (Criteria) this;
        }

        public Criteria andR2LessThan(String value) {
            addCriterion("r2 <", value, "r2");
            return (Criteria) this;
        }

        public Criteria andR2LessThanOrEqualTo(String value) {
            addCriterion("r2 <=", value, "r2");
            return (Criteria) this;
        }

        public Criteria andR2Like(String value) {
            addCriterion("r2 like", value, "r2");
            return (Criteria) this;
        }

        public Criteria andR2NotLike(String value) {
            addCriterion("r2 not like", value, "r2");
            return (Criteria) this;
        }

        public Criteria andR2In(List<String> values) {
            addCriterion("r2 in", values, "r2");
            return (Criteria) this;
        }

        public Criteria andR2NotIn(List<String> values) {
            addCriterion("r2 not in", values, "r2");
            return (Criteria) this;
        }

        public Criteria andR2Between(String value1, String value2) {
            addCriterion("r2 between", value1, value2, "r2");
            return (Criteria) this;
        }

        public Criteria andR2NotBetween(String value1, String value2) {
            addCriterion("r2 not between", value1, value2, "r2");
            return (Criteria) this;
        }

        public Criteria andR3IsNull() {
            addCriterion("r3 is null");
            return (Criteria) this;
        }

        public Criteria andR3IsNotNull() {
            addCriterion("r3 is not null");
            return (Criteria) this;
        }

        public Criteria andR3EqualTo(String value) {
            addCriterion("r3 =", value, "r3");
            return (Criteria) this;
        }

        public Criteria andR3NotEqualTo(String value) {
            addCriterion("r3 <>", value, "r3");
            return (Criteria) this;
        }

        public Criteria andR3GreaterThan(String value) {
            addCriterion("r3 >", value, "r3");
            return (Criteria) this;
        }

        public Criteria andR3GreaterThanOrEqualTo(String value) {
            addCriterion("r3 >=", value, "r3");
            return (Criteria) this;
        }

        public Criteria andR3LessThan(String value) {
            addCriterion("r3 <", value, "r3");
            return (Criteria) this;
        }

        public Criteria andR3LessThanOrEqualTo(String value) {
            addCriterion("r3 <=", value, "r3");
            return (Criteria) this;
        }

        public Criteria andR3Like(String value) {
            addCriterion("r3 like", value, "r3");
            return (Criteria) this;
        }

        public Criteria andR3NotLike(String value) {
            addCriterion("r3 not like", value, "r3");
            return (Criteria) this;
        }

        public Criteria andR3In(List<String> values) {
            addCriterion("r3 in", values, "r3");
            return (Criteria) this;
        }

        public Criteria andR3NotIn(List<String> values) {
            addCriterion("r3 not in", values, "r3");
            return (Criteria) this;
        }

        public Criteria andR3Between(String value1, String value2) {
            addCriterion("r3 between", value1, value2, "r3");
            return (Criteria) this;
        }

        public Criteria andR3NotBetween(String value1, String value2) {
            addCriterion("r3 not between", value1, value2, "r3");
            return (Criteria) this;
        }

        public Criteria andR4IsNull() {
            addCriterion("r4 is null");
            return (Criteria) this;
        }

        public Criteria andR4IsNotNull() {
            addCriterion("r4 is not null");
            return (Criteria) this;
        }

        public Criteria andR4EqualTo(String value) {
            addCriterion("r4 =", value, "r4");
            return (Criteria) this;
        }

        public Criteria andR4NotEqualTo(String value) {
            addCriterion("r4 <>", value, "r4");
            return (Criteria) this;
        }

        public Criteria andR4GreaterThan(String value) {
            addCriterion("r4 >", value, "r4");
            return (Criteria) this;
        }

        public Criteria andR4GreaterThanOrEqualTo(String value) {
            addCriterion("r4 >=", value, "r4");
            return (Criteria) this;
        }

        public Criteria andR4LessThan(String value) {
            addCriterion("r4 <", value, "r4");
            return (Criteria) this;
        }

        public Criteria andR4LessThanOrEqualTo(String value) {
            addCriterion("r4 <=", value, "r4");
            return (Criteria) this;
        }

        public Criteria andR4Like(String value) {
            addCriterion("r4 like", value, "r4");
            return (Criteria) this;
        }

        public Criteria andR4NotLike(String value) {
            addCriterion("r4 not like", value, "r4");
            return (Criteria) this;
        }

        public Criteria andR4In(List<String> values) {
            addCriterion("r4 in", values, "r4");
            return (Criteria) this;
        }

        public Criteria andR4NotIn(List<String> values) {
            addCriterion("r4 not in", values, "r4");
            return (Criteria) this;
        }

        public Criteria andR4Between(String value1, String value2) {
            addCriterion("r4 between", value1, value2, "r4");
            return (Criteria) this;
        }

        public Criteria andR4NotBetween(String value1, String value2) {
            addCriterion("r4 not between", value1, value2, "r4");
            return (Criteria) this;
        }

        public Criteria andR5IsNull() {
            addCriterion("r5 is null");
            return (Criteria) this;
        }

        public Criteria andR5IsNotNull() {
            addCriterion("r5 is not null");
            return (Criteria) this;
        }

        public Criteria andR5EqualTo(String value) {
            addCriterion("r5 =", value, "r5");
            return (Criteria) this;
        }

        public Criteria andR5NotEqualTo(String value) {
            addCriterion("r5 <>", value, "r5");
            return (Criteria) this;
        }

        public Criteria andR5GreaterThan(String value) {
            addCriterion("r5 >", value, "r5");
            return (Criteria) this;
        }

        public Criteria andR5GreaterThanOrEqualTo(String value) {
            addCriterion("r5 >=", value, "r5");
            return (Criteria) this;
        }

        public Criteria andR5LessThan(String value) {
            addCriterion("r5 <", value, "r5");
            return (Criteria) this;
        }

        public Criteria andR5LessThanOrEqualTo(String value) {
            addCriterion("r5 <=", value, "r5");
            return (Criteria) this;
        }

        public Criteria andR5Like(String value) {
            addCriterion("r5 like", value, "r5");
            return (Criteria) this;
        }

        public Criteria andR5NotLike(String value) {
            addCriterion("r5 not like", value, "r5");
            return (Criteria) this;
        }

        public Criteria andR5In(List<String> values) {
            addCriterion("r5 in", values, "r5");
            return (Criteria) this;
        }

        public Criteria andR5NotIn(List<String> values) {
            addCriterion("r5 not in", values, "r5");
            return (Criteria) this;
        }

        public Criteria andR5Between(String value1, String value2) {
            addCriterion("r5 between", value1, value2, "r5");
            return (Criteria) this;
        }

        public Criteria andR5NotBetween(String value1, String value2) {
            addCriterion("r5 not between", value1, value2, "r5");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table messageimg
     *
     * @mbggenerated do_not_delete_during_merge Mon Jan 02 17:35:41 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table messageimg
     *
     * @mbggenerated Mon Jan 02 17:35:41 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}