package com.edu.ccut.pojo;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class PersonExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table person
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table person
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table person
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table person
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	public PersonExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table person
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table person
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table person
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table person
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table person
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table person
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table person
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table person
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table person
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table person
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table person
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		protected void addCriterionForJDBCDate(String condition, Date value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value.getTime()), property);
		}

		protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property + " cannot be null or empty");
			}
			List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
			Iterator<Date> iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(iter.next().getTime()));
			}
			addCriterion(condition, dateList, property);
		}

		protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andPnameIsNull() {
			addCriterion("pname is null");
			return (Criteria) this;
		}

		public Criteria andPnameIsNotNull() {
			addCriterion("pname is not null");
			return (Criteria) this;
		}

		public Criteria andPnameEqualTo(String value) {
			addCriterion("pname =", value, "pname");
			return (Criteria) this;
		}

		public Criteria andPnameNotEqualTo(String value) {
			addCriterion("pname <>", value, "pname");
			return (Criteria) this;
		}

		public Criteria andPnameGreaterThan(String value) {
			addCriterion("pname >", value, "pname");
			return (Criteria) this;
		}

		public Criteria andPnameGreaterThanOrEqualTo(String value) {
			addCriterion("pname >=", value, "pname");
			return (Criteria) this;
		}

		public Criteria andPnameLessThan(String value) {
			addCriterion("pname <", value, "pname");
			return (Criteria) this;
		}

		public Criteria andPnameLessThanOrEqualTo(String value) {
			addCriterion("pname <=", value, "pname");
			return (Criteria) this;
		}

		public Criteria andPnameLike(String value) {
			addCriterion("pname like", value, "pname");
			return (Criteria) this;
		}

		public Criteria andPnameNotLike(String value) {
			addCriterion("pname not like", value, "pname");
			return (Criteria) this;
		}

		public Criteria andPnameIn(List<String> values) {
			addCriterion("pname in", values, "pname");
			return (Criteria) this;
		}

		public Criteria andPnameNotIn(List<String> values) {
			addCriterion("pname not in", values, "pname");
			return (Criteria) this;
		}

		public Criteria andPnameBetween(String value1, String value2) {
			addCriterion("pname between", value1, value2, "pname");
			return (Criteria) this;
		}

		public Criteria andPnameNotBetween(String value1, String value2) {
			addCriterion("pname not between", value1, value2, "pname");
			return (Criteria) this;
		}

		public Criteria andIdtypeIsNull() {
			addCriterion("idtype is null");
			return (Criteria) this;
		}

		public Criteria andIdtypeIsNotNull() {
			addCriterion("idtype is not null");
			return (Criteria) this;
		}

		public Criteria andIdtypeEqualTo(Integer value) {
			addCriterion("idtype =", value, "idtype");
			return (Criteria) this;
		}

		public Criteria andIdtypeNotEqualTo(Integer value) {
			addCriterion("idtype <>", value, "idtype");
			return (Criteria) this;
		}

		public Criteria andIdtypeGreaterThan(Integer value) {
			addCriterion("idtype >", value, "idtype");
			return (Criteria) this;
		}

		public Criteria andIdtypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("idtype >=", value, "idtype");
			return (Criteria) this;
		}

		public Criteria andIdtypeLessThan(Integer value) {
			addCriterion("idtype <", value, "idtype");
			return (Criteria) this;
		}

		public Criteria andIdtypeLessThanOrEqualTo(Integer value) {
			addCriterion("idtype <=", value, "idtype");
			return (Criteria) this;
		}

		public Criteria andIdtypeIn(List<Integer> values) {
			addCriterion("idtype in", values, "idtype");
			return (Criteria) this;
		}

		public Criteria andIdtypeNotIn(List<Integer> values) {
			addCriterion("idtype not in", values, "idtype");
			return (Criteria) this;
		}

		public Criteria andIdtypeBetween(Integer value1, Integer value2) {
			addCriterion("idtype between", value1, value2, "idtype");
			return (Criteria) this;
		}

		public Criteria andIdtypeNotBetween(Integer value1, Integer value2) {
			addCriterion("idtype not between", value1, value2, "idtype");
			return (Criteria) this;
		}

		public Criteria andIdnumIsNull() {
			addCriterion("idnum is null");
			return (Criteria) this;
		}

		public Criteria andIdnumIsNotNull() {
			addCriterion("idnum is not null");
			return (Criteria) this;
		}

		public Criteria andIdnumEqualTo(String value) {
			addCriterion("idnum =", value, "idnum");
			return (Criteria) this;
		}

		public Criteria andIdnumNotEqualTo(String value) {
			addCriterion("idnum <>", value, "idnum");
			return (Criteria) this;
		}

		public Criteria andIdnumGreaterThan(String value) {
			addCriterion("idnum >", value, "idnum");
			return (Criteria) this;
		}

		public Criteria andIdnumGreaterThanOrEqualTo(String value) {
			addCriterion("idnum >=", value, "idnum");
			return (Criteria) this;
		}

		public Criteria andIdnumLessThan(String value) {
			addCriterion("idnum <", value, "idnum");
			return (Criteria) this;
		}

		public Criteria andIdnumLessThanOrEqualTo(String value) {
			addCriterion("idnum <=", value, "idnum");
			return (Criteria) this;
		}

		public Criteria andIdnumLike(String value) {
			addCriterion("idnum like", value, "idnum");
			return (Criteria) this;
		}

		public Criteria andIdnumNotLike(String value) {
			addCriterion("idnum not like", value, "idnum");
			return (Criteria) this;
		}

		public Criteria andIdnumIn(List<String> values) {
			addCriterion("idnum in", values, "idnum");
			return (Criteria) this;
		}

		public Criteria andIdnumNotIn(List<String> values) {
			addCriterion("idnum not in", values, "idnum");
			return (Criteria) this;
		}

		public Criteria andIdnumBetween(String value1, String value2) {
			addCriterion("idnum between", value1, value2, "idnum");
			return (Criteria) this;
		}

		public Criteria andIdnumNotBetween(String value1, String value2) {
			addCriterion("idnum not between", value1, value2, "idnum");
			return (Criteria) this;
		}

		public Criteria andAccnumIsNull() {
			addCriterion("accnum is null");
			return (Criteria) this;
		}

		public Criteria andAccnumIsNotNull() {
			addCriterion("accnum is not null");
			return (Criteria) this;
		}

		public Criteria andAccnumEqualTo(String value) {
			addCriterion("accnum =", value, "accnum");
			return (Criteria) this;
		}

		public Criteria andAccnumNotEqualTo(String value) {
			addCriterion("accnum <>", value, "accnum");
			return (Criteria) this;
		}

		public Criteria andAccnumGreaterThan(String value) {
			addCriterion("accnum >", value, "accnum");
			return (Criteria) this;
		}

		public Criteria andAccnumGreaterThanOrEqualTo(String value) {
			addCriterion("accnum >=", value, "accnum");
			return (Criteria) this;
		}

		public Criteria andAccnumLessThan(String value) {
			addCriterion("accnum <", value, "accnum");
			return (Criteria) this;
		}

		public Criteria andAccnumLessThanOrEqualTo(String value) {
			addCriterion("accnum <=", value, "accnum");
			return (Criteria) this;
		}

		public Criteria andAccnumLike(String value) {
			addCriterion("accnum like", value, "accnum");
			return (Criteria) this;
		}

		public Criteria andAccnumNotLike(String value) {
			addCriterion("accnum not like", value, "accnum");
			return (Criteria) this;
		}

		public Criteria andAccnumIn(List<String> values) {
			addCriterion("accnum in", values, "accnum");
			return (Criteria) this;
		}

		public Criteria andAccnumNotIn(List<String> values) {
			addCriterion("accnum not in", values, "accnum");
			return (Criteria) this;
		}

		public Criteria andAccnumBetween(String value1, String value2) {
			addCriterion("accnum between", value1, value2, "accnum");
			return (Criteria) this;
		}

		public Criteria andAccnumNotBetween(String value1, String value2) {
			addCriterion("accnum not between", value1, value2, "accnum");
			return (Criteria) this;
		}

		public Criteria andUnitaccnumIsNull() {
			addCriterion("unitaccnum is null");
			return (Criteria) this;
		}

		public Criteria andUnitaccnumIsNotNull() {
			addCriterion("unitaccnum is not null");
			return (Criteria) this;
		}

		public Criteria andUnitaccnumEqualTo(String value) {
			addCriterion("unitaccnum =", value, "unitaccnum");
			return (Criteria) this;
		}

		public Criteria andUnitaccnumNotEqualTo(String value) {
			addCriterion("unitaccnum <>", value, "unitaccnum");
			return (Criteria) this;
		}

		public Criteria andUnitaccnumGreaterThan(String value) {
			addCriterion("unitaccnum >", value, "unitaccnum");
			return (Criteria) this;
		}

		public Criteria andUnitaccnumGreaterThanOrEqualTo(String value) {
			addCriterion("unitaccnum >=", value, "unitaccnum");
			return (Criteria) this;
		}

		public Criteria andUnitaccnumLessThan(String value) {
			addCriterion("unitaccnum <", value, "unitaccnum");
			return (Criteria) this;
		}

		public Criteria andUnitaccnumLessThanOrEqualTo(String value) {
			addCriterion("unitaccnum <=", value, "unitaccnum");
			return (Criteria) this;
		}

		public Criteria andUnitaccnumLike(String value) {
			addCriterion("unitaccnum like", value, "unitaccnum");
			return (Criteria) this;
		}

		public Criteria andUnitaccnumNotLike(String value) {
			addCriterion("unitaccnum not like", value, "unitaccnum");
			return (Criteria) this;
		}

		public Criteria andUnitaccnumIn(List<String> values) {
			addCriterion("unitaccnum in", values, "unitaccnum");
			return (Criteria) this;
		}

		public Criteria andUnitaccnumNotIn(List<String> values) {
			addCriterion("unitaccnum not in", values, "unitaccnum");
			return (Criteria) this;
		}

		public Criteria andUnitaccnumBetween(String value1, String value2) {
			addCriterion("unitaccnum between", value1, value2, "unitaccnum");
			return (Criteria) this;
		}

		public Criteria andUnitaccnumNotBetween(String value1, String value2) {
			addCriterion("unitaccnum not between", value1, value2, "unitaccnum");
			return (Criteria) this;
		}

		public Criteria andOpendateIsNull() {
			addCriterion("opendate is null");
			return (Criteria) this;
		}

		public Criteria andOpendateIsNotNull() {
			addCriterion("opendate is not null");
			return (Criteria) this;
		}

		public Criteria andOpendateEqualTo(Date value) {
			addCriterionForJDBCDate("opendate =", value, "opendate");
			return (Criteria) this;
		}

		public Criteria andOpendateNotEqualTo(Date value) {
			addCriterionForJDBCDate("opendate <>", value, "opendate");
			return (Criteria) this;
		}

		public Criteria andOpendateGreaterThan(Date value) {
			addCriterionForJDBCDate("opendate >", value, "opendate");
			return (Criteria) this;
		}

		public Criteria andOpendateGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("opendate >=", value, "opendate");
			return (Criteria) this;
		}

		public Criteria andOpendateLessThan(Date value) {
			addCriterionForJDBCDate("opendate <", value, "opendate");
			return (Criteria) this;
		}

		public Criteria andOpendateLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("opendate <=", value, "opendate");
			return (Criteria) this;
		}

		public Criteria andOpendateIn(List<Date> values) {
			addCriterionForJDBCDate("opendate in", values, "opendate");
			return (Criteria) this;
		}

		public Criteria andOpendateNotIn(List<Date> values) {
			addCriterionForJDBCDate("opendate not in", values, "opendate");
			return (Criteria) this;
		}

		public Criteria andOpendateBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("opendate between", value1, value2, "opendate");
			return (Criteria) this;
		}

		public Criteria andOpendateNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("opendate not between", value1, value2, "opendate");
			return (Criteria) this;
		}

		public Criteria andBalanceIsNull() {
			addCriterion("balance is null");
			return (Criteria) this;
		}

		public Criteria andBalanceIsNotNull() {
			addCriterion("balance is not null");
			return (Criteria) this;
		}

		public Criteria andBalanceEqualTo(BigDecimal value) {
			addCriterion("balance =", value, "balance");
			return (Criteria) this;
		}

		public Criteria andBalanceNotEqualTo(BigDecimal value) {
			addCriterion("balance <>", value, "balance");
			return (Criteria) this;
		}

		public Criteria andBalanceGreaterThan(BigDecimal value) {
			addCriterion("balance >", value, "balance");
			return (Criteria) this;
		}

		public Criteria andBalanceGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("balance >=", value, "balance");
			return (Criteria) this;
		}

		public Criteria andBalanceLessThan(BigDecimal value) {
			addCriterion("balance <", value, "balance");
			return (Criteria) this;
		}

		public Criteria andBalanceLessThanOrEqualTo(BigDecimal value) {
			addCriterion("balance <=", value, "balance");
			return (Criteria) this;
		}

		public Criteria andBalanceIn(List<BigDecimal> values) {
			addCriterion("balance in", values, "balance");
			return (Criteria) this;
		}

		public Criteria andBalanceNotIn(List<BigDecimal> values) {
			addCriterion("balance not in", values, "balance");
			return (Criteria) this;
		}

		public Criteria andBalanceBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("balance between", value1, value2, "balance");
			return (Criteria) this;
		}

		public Criteria andBalanceNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("balance not between", value1, value2, "balance");
			return (Criteria) this;
		}

		public Criteria andPeraccstateIsNull() {
			addCriterion("peraccstate is null");
			return (Criteria) this;
		}

		public Criteria andPeraccstateIsNotNull() {
			addCriterion("peraccstate is not null");
			return (Criteria) this;
		}

		public Criteria andPeraccstateEqualTo(String value) {
			addCriterion("peraccstate =", value, "peraccstate");
			return (Criteria) this;
		}

		public Criteria andPeraccstateNotEqualTo(String value) {
			addCriterion("peraccstate <>", value, "peraccstate");
			return (Criteria) this;
		}

		public Criteria andPeraccstateGreaterThan(String value) {
			addCriterion("peraccstate >", value, "peraccstate");
			return (Criteria) this;
		}

		public Criteria andPeraccstateGreaterThanOrEqualTo(String value) {
			addCriterion("peraccstate >=", value, "peraccstate");
			return (Criteria) this;
		}

		public Criteria andPeraccstateLessThan(String value) {
			addCriterion("peraccstate <", value, "peraccstate");
			return (Criteria) this;
		}

		public Criteria andPeraccstateLessThanOrEqualTo(String value) {
			addCriterion("peraccstate <=", value, "peraccstate");
			return (Criteria) this;
		}

		public Criteria andPeraccstateLike(String value) {
			addCriterion("peraccstate like", value, "peraccstate");
			return (Criteria) this;
		}

		public Criteria andPeraccstateNotLike(String value) {
			addCriterion("peraccstate not like", value, "peraccstate");
			return (Criteria) this;
		}

		public Criteria andPeraccstateIn(List<String> values) {
			addCriterion("peraccstate in", values, "peraccstate");
			return (Criteria) this;
		}

		public Criteria andPeraccstateNotIn(List<String> values) {
			addCriterion("peraccstate not in", values, "peraccstate");
			return (Criteria) this;
		}

		public Criteria andPeraccstateBetween(String value1, String value2) {
			addCriterion("peraccstate between", value1, value2, "peraccstate");
			return (Criteria) this;
		}

		public Criteria andPeraccstateNotBetween(String value1, String value2) {
			addCriterion("peraccstate not between", value1, value2, "peraccstate");
			return (Criteria) this;
		}

		public Criteria andBasenumberIsNull() {
			addCriterion("basenumber is null");
			return (Criteria) this;
		}

		public Criteria andBasenumberIsNotNull() {
			addCriterion("basenumber is not null");
			return (Criteria) this;
		}

		public Criteria andBasenumberEqualTo(BigDecimal value) {
			addCriterion("basenumber =", value, "basenumber");
			return (Criteria) this;
		}

		public Criteria andBasenumberNotEqualTo(BigDecimal value) {
			addCriterion("basenumber <>", value, "basenumber");
			return (Criteria) this;
		}

		public Criteria andBasenumberGreaterThan(BigDecimal value) {
			addCriterion("basenumber >", value, "basenumber");
			return (Criteria) this;
		}

		public Criteria andBasenumberGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("basenumber >=", value, "basenumber");
			return (Criteria) this;
		}

		public Criteria andBasenumberLessThan(BigDecimal value) {
			addCriterion("basenumber <", value, "basenumber");
			return (Criteria) this;
		}

		public Criteria andBasenumberLessThanOrEqualTo(BigDecimal value) {
			addCriterion("basenumber <=", value, "basenumber");
			return (Criteria) this;
		}

		public Criteria andBasenumberIn(List<BigDecimal> values) {
			addCriterion("basenumber in", values, "basenumber");
			return (Criteria) this;
		}

		public Criteria andBasenumberNotIn(List<BigDecimal> values) {
			addCriterion("basenumber not in", values, "basenumber");
			return (Criteria) this;
		}

		public Criteria andBasenumberBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("basenumber between", value1, value2, "basenumber");
			return (Criteria) this;
		}

		public Criteria andBasenumberNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("basenumber not between", value1, value2, "basenumber");
			return (Criteria) this;
		}

		public Criteria andUnitpropIsNull() {
			addCriterion("unitprop is null");
			return (Criteria) this;
		}

		public Criteria andUnitpropIsNotNull() {
			addCriterion("unitprop is not null");
			return (Criteria) this;
		}

		public Criteria andUnitpropEqualTo(BigDecimal value) {
			addCriterion("unitprop =", value, "unitprop");
			return (Criteria) this;
		}

		public Criteria andUnitpropNotEqualTo(BigDecimal value) {
			addCriterion("unitprop <>", value, "unitprop");
			return (Criteria) this;
		}

		public Criteria andUnitpropGreaterThan(BigDecimal value) {
			addCriterion("unitprop >", value, "unitprop");
			return (Criteria) this;
		}

		public Criteria andUnitpropGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("unitprop >=", value, "unitprop");
			return (Criteria) this;
		}

		public Criteria andUnitpropLessThan(BigDecimal value) {
			addCriterion("unitprop <", value, "unitprop");
			return (Criteria) this;
		}

		public Criteria andUnitpropLessThanOrEqualTo(BigDecimal value) {
			addCriterion("unitprop <=", value, "unitprop");
			return (Criteria) this;
		}

		public Criteria andUnitpropIn(List<BigDecimal> values) {
			addCriterion("unitprop in", values, "unitprop");
			return (Criteria) this;
		}

		public Criteria andUnitpropNotIn(List<BigDecimal> values) {
			addCriterion("unitprop not in", values, "unitprop");
			return (Criteria) this;
		}

		public Criteria andUnitpropBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("unitprop between", value1, value2, "unitprop");
			return (Criteria) this;
		}

		public Criteria andUnitpropNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("unitprop not between", value1, value2, "unitprop");
			return (Criteria) this;
		}

		public Criteria andIndipropIsNull() {
			addCriterion("indiprop is null");
			return (Criteria) this;
		}

		public Criteria andIndipropIsNotNull() {
			addCriterion("indiprop is not null");
			return (Criteria) this;
		}

		public Criteria andIndipropEqualTo(BigDecimal value) {
			addCriterion("indiprop =", value, "indiprop");
			return (Criteria) this;
		}

		public Criteria andIndipropNotEqualTo(BigDecimal value) {
			addCriterion("indiprop <>", value, "indiprop");
			return (Criteria) this;
		}

		public Criteria andIndipropGreaterThan(BigDecimal value) {
			addCriterion("indiprop >", value, "indiprop");
			return (Criteria) this;
		}

		public Criteria andIndipropGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("indiprop >=", value, "indiprop");
			return (Criteria) this;
		}

		public Criteria andIndipropLessThan(BigDecimal value) {
			addCriterion("indiprop <", value, "indiprop");
			return (Criteria) this;
		}

		public Criteria andIndipropLessThanOrEqualTo(BigDecimal value) {
			addCriterion("indiprop <=", value, "indiprop");
			return (Criteria) this;
		}

		public Criteria andIndipropIn(List<BigDecimal> values) {
			addCriterion("indiprop in", values, "indiprop");
			return (Criteria) this;
		}

		public Criteria andIndipropNotIn(List<BigDecimal> values) {
			addCriterion("indiprop not in", values, "indiprop");
			return (Criteria) this;
		}

		public Criteria andIndipropBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("indiprop between", value1, value2, "indiprop");
			return (Criteria) this;
		}

		public Criteria andIndipropNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("indiprop not between", value1, value2, "indiprop");
			return (Criteria) this;
		}

		public Criteria andLastpaydateIsNull() {
			addCriterion("lastpaydate is null");
			return (Criteria) this;
		}

		public Criteria andLastpaydateIsNotNull() {
			addCriterion("lastpaydate is not null");
			return (Criteria) this;
		}

		public Criteria andLastpaydateEqualTo(Date value) {
			addCriterionForJDBCDate("lastpaydate =", value, "lastpaydate");
			return (Criteria) this;
		}

		public Criteria andLastpaydateNotEqualTo(Date value) {
			addCriterionForJDBCDate("lastpaydate <>", value, "lastpaydate");
			return (Criteria) this;
		}

		public Criteria andLastpaydateGreaterThan(Date value) {
			addCriterionForJDBCDate("lastpaydate >", value, "lastpaydate");
			return (Criteria) this;
		}

		public Criteria andLastpaydateGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("lastpaydate >=", value, "lastpaydate");
			return (Criteria) this;
		}

		public Criteria andLastpaydateLessThan(Date value) {
			addCriterionForJDBCDate("lastpaydate <", value, "lastpaydate");
			return (Criteria) this;
		}

		public Criteria andLastpaydateLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("lastpaydate <=", value, "lastpaydate");
			return (Criteria) this;
		}

		public Criteria andLastpaydateIn(List<Date> values) {
			addCriterionForJDBCDate("lastpaydate in", values, "lastpaydate");
			return (Criteria) this;
		}

		public Criteria andLastpaydateNotIn(List<Date> values) {
			addCriterionForJDBCDate("lastpaydate not in", values, "lastpaydate");
			return (Criteria) this;
		}

		public Criteria andLastpaydateBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("lastpaydate between", value1, value2, "lastpaydate");
			return (Criteria) this;
		}

		public Criteria andLastpaydateNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("lastpaydate not between", value1, value2, "lastpaydate");
			return (Criteria) this;
		}

		public Criteria andUnitmonpaysumIsNull() {
			addCriterion("unitmonpaysum is null");
			return (Criteria) this;
		}

		public Criteria andUnitmonpaysumIsNotNull() {
			addCriterion("unitmonpaysum is not null");
			return (Criteria) this;
		}

		public Criteria andUnitmonpaysumEqualTo(BigDecimal value) {
			addCriterion("unitmonpaysum =", value, "unitmonpaysum");
			return (Criteria) this;
		}

		public Criteria andUnitmonpaysumNotEqualTo(BigDecimal value) {
			addCriterion("unitmonpaysum <>", value, "unitmonpaysum");
			return (Criteria) this;
		}

		public Criteria andUnitmonpaysumGreaterThan(BigDecimal value) {
			addCriterion("unitmonpaysum >", value, "unitmonpaysum");
			return (Criteria) this;
		}

		public Criteria andUnitmonpaysumGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("unitmonpaysum >=", value, "unitmonpaysum");
			return (Criteria) this;
		}

		public Criteria andUnitmonpaysumLessThan(BigDecimal value) {
			addCriterion("unitmonpaysum <", value, "unitmonpaysum");
			return (Criteria) this;
		}

		public Criteria andUnitmonpaysumLessThanOrEqualTo(BigDecimal value) {
			addCriterion("unitmonpaysum <=", value, "unitmonpaysum");
			return (Criteria) this;
		}

		public Criteria andUnitmonpaysumIn(List<BigDecimal> values) {
			addCriterion("unitmonpaysum in", values, "unitmonpaysum");
			return (Criteria) this;
		}

		public Criteria andUnitmonpaysumNotIn(List<BigDecimal> values) {
			addCriterion("unitmonpaysum not in", values, "unitmonpaysum");
			return (Criteria) this;
		}

		public Criteria andUnitmonpaysumBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("unitmonpaysum between", value1, value2, "unitmonpaysum");
			return (Criteria) this;
		}

		public Criteria andUnitmonpaysumNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("unitmonpaysum not between", value1, value2, "unitmonpaysum");
			return (Criteria) this;
		}

		public Criteria andPermonpaysumIsNull() {
			addCriterion("permonpaysum is null");
			return (Criteria) this;
		}

		public Criteria andPermonpaysumIsNotNull() {
			addCriterion("permonpaysum is not null");
			return (Criteria) this;
		}

		public Criteria andPermonpaysumEqualTo(BigDecimal value) {
			addCriterion("permonpaysum =", value, "permonpaysum");
			return (Criteria) this;
		}

		public Criteria andPermonpaysumNotEqualTo(BigDecimal value) {
			addCriterion("permonpaysum <>", value, "permonpaysum");
			return (Criteria) this;
		}

		public Criteria andPermonpaysumGreaterThan(BigDecimal value) {
			addCriterion("permonpaysum >", value, "permonpaysum");
			return (Criteria) this;
		}

		public Criteria andPermonpaysumGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("permonpaysum >=", value, "permonpaysum");
			return (Criteria) this;
		}

		public Criteria andPermonpaysumLessThan(BigDecimal value) {
			addCriterion("permonpaysum <", value, "permonpaysum");
			return (Criteria) this;
		}

		public Criteria andPermonpaysumLessThanOrEqualTo(BigDecimal value) {
			addCriterion("permonpaysum <=", value, "permonpaysum");
			return (Criteria) this;
		}

		public Criteria andPermonpaysumIn(List<BigDecimal> values) {
			addCriterion("permonpaysum in", values, "permonpaysum");
			return (Criteria) this;
		}

		public Criteria andPermonpaysumNotIn(List<BigDecimal> values) {
			addCriterion("permonpaysum not in", values, "permonpaysum");
			return (Criteria) this;
		}

		public Criteria andPermonpaysumBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("permonpaysum between", value1, value2, "permonpaysum");
			return (Criteria) this;
		}

		public Criteria andPermonpaysumNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("permonpaysum not between", value1, value2, "permonpaysum");
			return (Criteria) this;
		}

		public Criteria andYpayamtIsNull() {
			addCriterion("ypayamt is null");
			return (Criteria) this;
		}

		public Criteria andYpayamtIsNotNull() {
			addCriterion("ypayamt is not null");
			return (Criteria) this;
		}

		public Criteria andYpayamtEqualTo(BigDecimal value) {
			addCriterion("ypayamt =", value, "ypayamt");
			return (Criteria) this;
		}

		public Criteria andYpayamtNotEqualTo(BigDecimal value) {
			addCriterion("ypayamt <>", value, "ypayamt");
			return (Criteria) this;
		}

		public Criteria andYpayamtGreaterThan(BigDecimal value) {
			addCriterion("ypayamt >", value, "ypayamt");
			return (Criteria) this;
		}

		public Criteria andYpayamtGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("ypayamt >=", value, "ypayamt");
			return (Criteria) this;
		}

		public Criteria andYpayamtLessThan(BigDecimal value) {
			addCriterion("ypayamt <", value, "ypayamt");
			return (Criteria) this;
		}

		public Criteria andYpayamtLessThanOrEqualTo(BigDecimal value) {
			addCriterion("ypayamt <=", value, "ypayamt");
			return (Criteria) this;
		}

		public Criteria andYpayamtIn(List<BigDecimal> values) {
			addCriterion("ypayamt in", values, "ypayamt");
			return (Criteria) this;
		}

		public Criteria andYpayamtNotIn(List<BigDecimal> values) {
			addCriterion("ypayamt not in", values, "ypayamt");
			return (Criteria) this;
		}

		public Criteria andYpayamtBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("ypayamt between", value1, value2, "ypayamt");
			return (Criteria) this;
		}

		public Criteria andYpayamtNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("ypayamt not between", value1, value2, "ypayamt");
			return (Criteria) this;
		}

		public Criteria andYdrawamtIsNull() {
			addCriterion("ydrawamt is null");
			return (Criteria) this;
		}

		public Criteria andYdrawamtIsNotNull() {
			addCriterion("ydrawamt is not null");
			return (Criteria) this;
		}

		public Criteria andYdrawamtEqualTo(BigDecimal value) {
			addCriterion("ydrawamt =", value, "ydrawamt");
			return (Criteria) this;
		}

		public Criteria andYdrawamtNotEqualTo(BigDecimal value) {
			addCriterion("ydrawamt <>", value, "ydrawamt");
			return (Criteria) this;
		}

		public Criteria andYdrawamtGreaterThan(BigDecimal value) {
			addCriterion("ydrawamt >", value, "ydrawamt");
			return (Criteria) this;
		}

		public Criteria andYdrawamtGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("ydrawamt >=", value, "ydrawamt");
			return (Criteria) this;
		}

		public Criteria andYdrawamtLessThan(BigDecimal value) {
			addCriterion("ydrawamt <", value, "ydrawamt");
			return (Criteria) this;
		}

		public Criteria andYdrawamtLessThanOrEqualTo(BigDecimal value) {
			addCriterion("ydrawamt <=", value, "ydrawamt");
			return (Criteria) this;
		}

		public Criteria andYdrawamtIn(List<BigDecimal> values) {
			addCriterion("ydrawamt in", values, "ydrawamt");
			return (Criteria) this;
		}

		public Criteria andYdrawamtNotIn(List<BigDecimal> values) {
			addCriterion("ydrawamt not in", values, "ydrawamt");
			return (Criteria) this;
		}

		public Criteria andYdrawamtBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("ydrawamt between", value1, value2, "ydrawamt");
			return (Criteria) this;
		}

		public Criteria andYdrawamtNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("ydrawamt not between", value1, value2, "ydrawamt");
			return (Criteria) this;
		}

		public Criteria andYinterestbalIsNull() {
			addCriterion("yinterestbal is null");
			return (Criteria) this;
		}

		public Criteria andYinterestbalIsNotNull() {
			addCriterion("yinterestbal is not null");
			return (Criteria) this;
		}

		public Criteria andYinterestbalEqualTo(BigDecimal value) {
			addCriterion("yinterestbal =", value, "yinterestbal");
			return (Criteria) this;
		}

		public Criteria andYinterestbalNotEqualTo(BigDecimal value) {
			addCriterion("yinterestbal <>", value, "yinterestbal");
			return (Criteria) this;
		}

		public Criteria andYinterestbalGreaterThan(BigDecimal value) {
			addCriterion("yinterestbal >", value, "yinterestbal");
			return (Criteria) this;
		}

		public Criteria andYinterestbalGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("yinterestbal >=", value, "yinterestbal");
			return (Criteria) this;
		}

		public Criteria andYinterestbalLessThan(BigDecimal value) {
			addCriterion("yinterestbal <", value, "yinterestbal");
			return (Criteria) this;
		}

		public Criteria andYinterestbalLessThanOrEqualTo(BigDecimal value) {
			addCriterion("yinterestbal <=", value, "yinterestbal");
			return (Criteria) this;
		}

		public Criteria andYinterestbalIn(List<BigDecimal> values) {
			addCriterion("yinterestbal in", values, "yinterestbal");
			return (Criteria) this;
		}

		public Criteria andYinterestbalNotIn(List<BigDecimal> values) {
			addCriterion("yinterestbal not in", values, "yinterestbal");
			return (Criteria) this;
		}

		public Criteria andYinterestbalBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("yinterestbal between", value1, value2, "yinterestbal");
			return (Criteria) this;
		}

		public Criteria andYinterestbalNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("yinterestbal not between", value1, value2, "yinterestbal");
			return (Criteria) this;
		}

		public Criteria andInstcodeIsNull() {
			addCriterion("instcode is null");
			return (Criteria) this;
		}

		public Criteria andInstcodeIsNotNull() {
			addCriterion("instcode is not null");
			return (Criteria) this;
		}

		public Criteria andInstcodeEqualTo(String value) {
			addCriterion("instcode =", value, "instcode");
			return (Criteria) this;
		}

		public Criteria andInstcodeNotEqualTo(String value) {
			addCriterion("instcode <>", value, "instcode");
			return (Criteria) this;
		}

		public Criteria andInstcodeGreaterThan(String value) {
			addCriterion("instcode >", value, "instcode");
			return (Criteria) this;
		}

		public Criteria andInstcodeGreaterThanOrEqualTo(String value) {
			addCriterion("instcode >=", value, "instcode");
			return (Criteria) this;
		}

		public Criteria andInstcodeLessThan(String value) {
			addCriterion("instcode <", value, "instcode");
			return (Criteria) this;
		}

		public Criteria andInstcodeLessThanOrEqualTo(String value) {
			addCriterion("instcode <=", value, "instcode");
			return (Criteria) this;
		}

		public Criteria andInstcodeLike(String value) {
			addCriterion("instcode like", value, "instcode");
			return (Criteria) this;
		}

		public Criteria andInstcodeNotLike(String value) {
			addCriterion("instcode not like", value, "instcode");
			return (Criteria) this;
		}

		public Criteria andInstcodeIn(List<String> values) {
			addCriterion("instcode in", values, "instcode");
			return (Criteria) this;
		}

		public Criteria andInstcodeNotIn(List<String> values) {
			addCriterion("instcode not in", values, "instcode");
			return (Criteria) this;
		}

		public Criteria andInstcodeBetween(String value1, String value2) {
			addCriterion("instcode between", value1, value2, "instcode");
			return (Criteria) this;
		}

		public Criteria andInstcodeNotBetween(String value1, String value2) {
			addCriterion("instcode not between", value1, value2, "instcode");
			return (Criteria) this;
		}

		public Criteria andOpIsNull() {
			addCriterion("op is null");
			return (Criteria) this;
		}

		public Criteria andOpIsNotNull() {
			addCriterion("op is not null");
			return (Criteria) this;
		}

		public Criteria andOpEqualTo(String value) {
			addCriterion("op =", value, "op");
			return (Criteria) this;
		}

		public Criteria andOpNotEqualTo(String value) {
			addCriterion("op <>", value, "op");
			return (Criteria) this;
		}

		public Criteria andOpGreaterThan(String value) {
			addCriterion("op >", value, "op");
			return (Criteria) this;
		}

		public Criteria andOpGreaterThanOrEqualTo(String value) {
			addCriterion("op >=", value, "op");
			return (Criteria) this;
		}

		public Criteria andOpLessThan(String value) {
			addCriterion("op <", value, "op");
			return (Criteria) this;
		}

		public Criteria andOpLessThanOrEqualTo(String value) {
			addCriterion("op <=", value, "op");
			return (Criteria) this;
		}

		public Criteria andOpLike(String value) {
			addCriterion("op like", value, "op");
			return (Criteria) this;
		}

		public Criteria andOpNotLike(String value) {
			addCriterion("op not like", value, "op");
			return (Criteria) this;
		}

		public Criteria andOpIn(List<String> values) {
			addCriterion("op in", values, "op");
			return (Criteria) this;
		}

		public Criteria andOpNotIn(List<String> values) {
			addCriterion("op not in", values, "op");
			return (Criteria) this;
		}

		public Criteria andOpBetween(String value1, String value2) {
			addCriterion("op between", value1, value2, "op");
			return (Criteria) this;
		}

		public Criteria andOpNotBetween(String value1, String value2) {
			addCriterion("op not between", value1, value2, "op");
			return (Criteria) this;
		}

		public Criteria andRemarkIsNull() {
			addCriterion("remark is null");
			return (Criteria) this;
		}

		public Criteria andRemarkIsNotNull() {
			addCriterion("remark is not null");
			return (Criteria) this;
		}

		public Criteria andRemarkEqualTo(String value) {
			addCriterion("remark =", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotEqualTo(String value) {
			addCriterion("remark <>", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkGreaterThan(String value) {
			addCriterion("remark >", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkGreaterThanOrEqualTo(String value) {
			addCriterion("remark >=", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLessThan(String value) {
			addCriterion("remark <", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLessThanOrEqualTo(String value) {
			addCriterion("remark <=", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLike(String value) {
			addCriterion("remark like", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotLike(String value) {
			addCriterion("remark not like", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkIn(List<String> values) {
			addCriterion("remark in", values, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotIn(List<String> values) {
			addCriterion("remark not in", values, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkBetween(String value1, String value2) {
			addCriterion("remark between", value1, value2, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotBetween(String value1, String value2) {
			addCriterion("remark not between", value1, value2, "remark");
			return (Criteria) this;
		}

		public Criteria andR1IsNull() {
			addCriterion("r1 is null");
			return (Criteria) this;
		}

		public Criteria andR1IsNotNull() {
			addCriterion("r1 is not null");
			return (Criteria) this;
		}

		public Criteria andR1EqualTo(String value) {
			addCriterion("r1 =", value, "r1");
			return (Criteria) this;
		}

		public Criteria andR1NotEqualTo(String value) {
			addCriterion("r1 <>", value, "r1");
			return (Criteria) this;
		}

		public Criteria andR1GreaterThan(String value) {
			addCriterion("r1 >", value, "r1");
			return (Criteria) this;
		}

		public Criteria andR1GreaterThanOrEqualTo(String value) {
			addCriterion("r1 >=", value, "r1");
			return (Criteria) this;
		}

		public Criteria andR1LessThan(String value) {
			addCriterion("r1 <", value, "r1");
			return (Criteria) this;
		}

		public Criteria andR1LessThanOrEqualTo(String value) {
			addCriterion("r1 <=", value, "r1");
			return (Criteria) this;
		}

		public Criteria andR1Like(String value) {
			addCriterion("r1 like", value, "r1");
			return (Criteria) this;
		}

		public Criteria andR1NotLike(String value) {
			addCriterion("r1 not like", value, "r1");
			return (Criteria) this;
		}

		public Criteria andR1In(List<String> values) {
			addCriterion("r1 in", values, "r1");
			return (Criteria) this;
		}

		public Criteria andR1NotIn(List<String> values) {
			addCriterion("r1 not in", values, "r1");
			return (Criteria) this;
		}

		public Criteria andR1Between(String value1, String value2) {
			addCriterion("r1 between", value1, value2, "r1");
			return (Criteria) this;
		}

		public Criteria andR1NotBetween(String value1, String value2) {
			addCriterion("r1 not between", value1, value2, "r1");
			return (Criteria) this;
		}

		public Criteria andR2IsNull() {
			addCriterion("r2 is null");
			return (Criteria) this;
		}

		public Criteria andR2IsNotNull() {
			addCriterion("r2 is not null");
			return (Criteria) this;
		}

		public Criteria andR2EqualTo(String value) {
			addCriterion("r2 =", value, "r2");
			return (Criteria) this;
		}

		public Criteria andR2NotEqualTo(String value) {
			addCriterion("r2 <>", value, "r2");
			return (Criteria) this;
		}

		public Criteria andR2GreaterThan(String value) {
			addCriterion("r2 >", value, "r2");
			return (Criteria) this;
		}

		public Criteria andR2GreaterThanOrEqualTo(String value) {
			addCriterion("r2 >=", value, "r2");
			return (Criteria) this;
		}

		public Criteria andR2LessThan(String value) {
			addCriterion("r2 <", value, "r2");
			return (Criteria) this;
		}

		public Criteria andR2LessThanOrEqualTo(String value) {
			addCriterion("r2 <=", value, "r2");
			return (Criteria) this;
		}

		public Criteria andR2Like(String value) {
			addCriterion("r2 like", value, "r2");
			return (Criteria) this;
		}

		public Criteria andR2NotLike(String value) {
			addCriterion("r2 not like", value, "r2");
			return (Criteria) this;
		}

		public Criteria andR2In(List<String> values) {
			addCriterion("r2 in", values, "r2");
			return (Criteria) this;
		}

		public Criteria andR2NotIn(List<String> values) {
			addCriterion("r2 not in", values, "r2");
			return (Criteria) this;
		}

		public Criteria andR2Between(String value1, String value2) {
			addCriterion("r2 between", value1, value2, "r2");
			return (Criteria) this;
		}

		public Criteria andR2NotBetween(String value1, String value2) {
			addCriterion("r2 not between", value1, value2, "r2");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table person
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table person
     *
     * @mbggenerated do_not_delete_during_merge Mon Jul 11 15:16:37 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}