package com.edu.ccut.pojo;

public class Systemseq {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column systemseq.id
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column systemseq.seqname
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	private String seqname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column systemseq.seq
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	private Integer seq;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column systemseq.maxseq
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	private Integer maxseq;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column systemseq.depict
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	private String depict;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column systemseq.r1
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	private String r1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column systemseq.r2
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	private String r2;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column systemseq.id
	 * @return  the value of systemseq.id
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column systemseq.id
	 * @param id  the value for systemseq.id
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column systemseq.seqname
	 * @return  the value of systemseq.seqname
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	public String getSeqname() {
		return seqname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column systemseq.seqname
	 * @param seqname  the value for systemseq.seqname
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	public void setSeqname(String seqname) {
		this.seqname = seqname == null ? null : seqname.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column systemseq.seq
	 * @return  the value of systemseq.seq
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	public Integer getSeq() {
		return seq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column systemseq.seq
	 * @param seq  the value for systemseq.seq
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	public void setSeq(Integer seq) {
		this.seq = seq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column systemseq.maxseq
	 * @return  the value of systemseq.maxseq
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	public Integer getMaxseq() {
		return maxseq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column systemseq.maxseq
	 * @param maxseq  the value for systemseq.maxseq
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	public void setMaxseq(Integer maxseq) {
		this.maxseq = maxseq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column systemseq.depict
	 * @return  the value of systemseq.depict
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	public String getDepict() {
		return depict;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column systemseq.depict
	 * @param depict  the value for systemseq.depict
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	public void setDepict(String depict) {
		this.depict = depict == null ? null : depict.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column systemseq.r1
	 * @return  the value of systemseq.r1
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	public String getR1() {
		return r1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column systemseq.r1
	 * @param r1  the value for systemseq.r1
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	public void setR1(String r1) {
		this.r1 = r1 == null ? null : r1.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column systemseq.r2
	 * @return  the value of systemseq.r2
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	public String getR2() {
		return r2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column systemseq.r2
	 * @param r2  the value for systemseq.r2
	 * @mbggenerated  Tue Jul 12 09:39:33 CST 2016
	 */
	public void setR2(String r2) {
		this.r2 = r2 == null ? null : r2.trim();
	}
}